// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: category.proto

package foodfoliov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Category message
type Category struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug       string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ParentId   *string                `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Timestamps *Timestamps            `protobuf:"bytes,5,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	// Optional relations
	Parent        *Category   `protobuf:"bytes,6,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	Children      []*Category `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	ItemCount     int32       `protobuf:"varint,8,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"` // Number of items in this category
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Category) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *Category) GetParent() *Category {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Category) GetChildren() []*Category {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Category) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

// Create category request
type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

// Create category response
type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

// Get category response
type GetCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResponse) Reset() {
	*x = GetCategoryResponse{}
	mi := &file_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResponse) ProtoMessage() {}

func (x *GetCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{3}
}

func (x *GetCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

// List categories request
type ListCategoriesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentId        *string                `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`                 // Filter by parent (null = root categories)
	IncludeChildren bool                   `protobuf:"varint,2,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"` // Include children in response
	Pagination      *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	DeletedFilter   *DeletedFilter         `protobuf:"bytes,4,opt,name=deleted_filter,json=deletedFilter,proto3" json:"deleted_filter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{4}
}

func (x *ListCategoriesRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *ListCategoriesRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

func (x *ListCategoriesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCategoriesRequest) GetDeletedFilter() *DeletedFilter {
	if x != nil {
		return x.DeletedFilter
	}
	return nil
}

// List categories response
type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{5}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListCategoriesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Update category request
type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ParentId      *string                `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"` // Set to empty string to remove parent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

// Update category response
type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_category_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

// Get category tree request
type GetCategoryTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        *string                `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3,oneof" json:"root_id,omitempty"`  // Start from specific category, or null for full tree
	MaxDepth      int32                  `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // Maximum depth to fetch (0 = unlimited)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryTreeRequest) Reset() {
	*x = GetCategoryTreeRequest{}
	mi := &file_category_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTreeRequest) ProtoMessage() {}

func (x *GetCategoryTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTreeRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryTreeRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{8}
}

func (x *GetCategoryTreeRequest) GetRootId() string {
	if x != nil && x.RootId != nil {
		return *x.RootId
	}
	return ""
}

func (x *GetCategoryTreeRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// Get category tree response
type GetCategoryTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"` // Root categories with nested children
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryTreeResponse) Reset() {
	*x = GetCategoryTreeResponse{}
	mi := &file_category_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTreeResponse) ProtoMessage() {}

func (x *GetCategoryTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTreeResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryTreeResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{9}
}

func (x *GetCategoryTreeResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_category_proto protoreflect.FileDescriptor

const file_category_proto_rawDesc = "" +
	"\n" +
	"\x0ecategory.proto\x12\ffoodfolio.v1\x1a\fcommon.proto\"\xbf\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x00R\bparentId\x88\x01\x01\x128\n" +
	"\n" +
	"timestamps\x18\x05 \x01(\v2\x18.foodfolio.v1.TimestampsR\n" +
	"timestamps\x123\n" +
	"\x06parent\x18\x06 \x01(\v2\x16.foodfolio.v1.CategoryH\x01R\x06parent\x88\x01\x01\x122\n" +
	"\bchildren\x18\a \x03(\v2\x16.foodfolio.v1.CategoryR\bchildren\x12\x1d\n" +
	"\n" +
	"item_count\x18\b \x01(\x05R\titemCountB\f\n" +
	"\n" +
	"_parent_idB\t\n" +
	"\a_parent\"[\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"L\n" +
	"\x16CreateCategoryResponse\x122\n" +
	"\bcategory\x18\x01 \x01(\v2\x16.foodfolio.v1.CategoryR\bcategory\"I\n" +
	"\x13GetCategoryResponse\x122\n" +
	"\bcategory\x18\x01 \x01(\v2\x16.foodfolio.v1.CategoryR\bcategory\"\xf7\x01\n" +
	"\x15ListCategoriesRequest\x12 \n" +
	"\tparent_id\x18\x01 \x01(\tH\x00R\bparentId\x88\x01\x01\x12)\n" +
	"\x10include_children\x18\x02 \x01(\bR\x0fincludeChildren\x12?\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1f.foodfolio.v1.PaginationRequestR\n" +
	"pagination\x12B\n" +
	"\x0edeleted_filter\x18\x04 \x01(\v2\x1b.foodfolio.v1.DeletedFilterR\rdeletedFilterB\f\n" +
	"\n" +
	"_parent_id\"\x92\x01\n" +
	"\x16ListCategoriesResponse\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.foodfolio.v1.CategoryR\n" +
	"categories\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .foodfolio.v1.PaginationResponseR\n" +
	"pagination\"y\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\tH\x01R\bparentId\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_parent_id\"L\n" +
	"\x16UpdateCategoryResponse\x122\n" +
	"\bcategory\x18\x01 \x01(\v2\x16.foodfolio.v1.CategoryR\bcategory\"_\n" +
	"\x16GetCategoryTreeRequest\x12\x1c\n" +
	"\aroot_id\x18\x01 \x01(\tH\x00R\x06rootId\x88\x01\x01\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepthB\n" +
	"\n" +
	"\b_root_id\"Q\n" +
	"\x17GetCategoryTreeResponse\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.foodfolio.v1.CategoryR\n" +
	"categories2\x9d\x04\n" +
	"\x0fCategoryService\x12[\n" +
	"\x0eCreateCategory\x12#.foodfolio.v1.CreateCategoryRequest\x1a$.foodfolio.v1.CreateCategoryResponse\x12I\n" +
	"\vGetCategory\x12\x17.foodfolio.v1.IdRequest\x1a!.foodfolio.v1.GetCategoryResponse\x12[\n" +
	"\x0eListCategories\x12#.foodfolio.v1.ListCategoriesRequest\x1a$.foodfolio.v1.ListCategoriesResponse\x12[\n" +
	"\x0eUpdateCategory\x12#.foodfolio.v1.UpdateCategoryRequest\x1a$.foodfolio.v1.UpdateCategoryResponse\x12H\n" +
	"\x0eDeleteCategory\x12\x17.foodfolio.v1.IdRequest\x1a\x1d.foodfolio.v1.SuccessResponse\x12^\n" +
	"\x0fGetCategoryTree\x12$.foodfolio.v1.GetCategoryTreeRequest\x1a%.foodfolio.v1.GetCategoryTreeResponseBJZHtoxictoast/services/foodfolio-service/api/proto/foodfolio/v1;foodfoliov1b\x06proto3"

var (
	file_category_proto_rawDescOnce sync.Once
	file_category_proto_rawDescData []byte
)

func file_category_proto_rawDescGZIP() []byte {
	file_category_proto_rawDescOnce.Do(func() {
		file_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_proto_rawDesc), len(file_category_proto_rawDesc)))
	})
	return file_category_proto_rawDescData
}

var file_category_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_category_proto_goTypes = []any{
	(*Category)(nil),                // 0: foodfolio.v1.Category
	(*CreateCategoryRequest)(nil),   // 1: foodfolio.v1.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),  // 2: foodfolio.v1.CreateCategoryResponse
	(*GetCategoryResponse)(nil),     // 3: foodfolio.v1.GetCategoryResponse
	(*ListCategoriesRequest)(nil),   // 4: foodfolio.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),  // 5: foodfolio.v1.ListCategoriesResponse
	(*UpdateCategoryRequest)(nil),   // 6: foodfolio.v1.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),  // 7: foodfolio.v1.UpdateCategoryResponse
	(*GetCategoryTreeRequest)(nil),  // 8: foodfolio.v1.GetCategoryTreeRequest
	(*GetCategoryTreeResponse)(nil), // 9: foodfolio.v1.GetCategoryTreeResponse
	(*Timestamps)(nil),              // 10: foodfolio.v1.Timestamps
	(*PaginationRequest)(nil),       // 11: foodfolio.v1.PaginationRequest
	(*DeletedFilter)(nil),           // 12: foodfolio.v1.DeletedFilter
	(*PaginationResponse)(nil),      // 13: foodfolio.v1.PaginationResponse
	(*IdRequest)(nil),               // 14: foodfolio.v1.IdRequest
	(*SuccessResponse)(nil),         // 15: foodfolio.v1.SuccessResponse
}
var file_category_proto_depIdxs = []int32{
	10, // 0: foodfolio.v1.Category.timestamps:type_name -> foodfolio.v1.Timestamps
	0,  // 1: foodfolio.v1.Category.parent:type_name -> foodfolio.v1.Category
	0,  // 2: foodfolio.v1.Category.children:type_name -> foodfolio.v1.Category
	0,  // 3: foodfolio.v1.CreateCategoryResponse.category:type_name -> foodfolio.v1.Category
	0,  // 4: foodfolio.v1.GetCategoryResponse.category:type_name -> foodfolio.v1.Category
	11, // 5: foodfolio.v1.ListCategoriesRequest.pagination:type_name -> foodfolio.v1.PaginationRequest
	12, // 6: foodfolio.v1.ListCategoriesRequest.deleted_filter:type_name -> foodfolio.v1.DeletedFilter
	0,  // 7: foodfolio.v1.ListCategoriesResponse.categories:type_name -> foodfolio.v1.Category
	13, // 8: foodfolio.v1.ListCategoriesResponse.pagination:type_name -> foodfolio.v1.PaginationResponse
	0,  // 9: foodfolio.v1.UpdateCategoryResponse.category:type_name -> foodfolio.v1.Category
	0,  // 10: foodfolio.v1.GetCategoryTreeResponse.categories:type_name -> foodfolio.v1.Category
	1,  // 11: foodfolio.v1.CategoryService.CreateCategory:input_type -> foodfolio.v1.CreateCategoryRequest
	14, // 12: foodfolio.v1.CategoryService.GetCategory:input_type -> foodfolio.v1.IdRequest
	4,  // 13: foodfolio.v1.CategoryService.ListCategories:input_type -> foodfolio.v1.ListCategoriesRequest
	6,  // 14: foodfolio.v1.CategoryService.UpdateCategory:input_type -> foodfolio.v1.UpdateCategoryRequest
	14, // 15: foodfolio.v1.CategoryService.DeleteCategory:input_type -> foodfolio.v1.IdRequest
	8,  // 16: foodfolio.v1.CategoryService.GetCategoryTree:input_type -> foodfolio.v1.GetCategoryTreeRequest
	2,  // 17: foodfolio.v1.CategoryService.CreateCategory:output_type -> foodfolio.v1.CreateCategoryResponse
	3,  // 18: foodfolio.v1.CategoryService.GetCategory:output_type -> foodfolio.v1.GetCategoryResponse
	5,  // 19: foodfolio.v1.CategoryService.ListCategories:output_type -> foodfolio.v1.ListCategoriesResponse
	7,  // 20: foodfolio.v1.CategoryService.UpdateCategory:output_type -> foodfolio.v1.UpdateCategoryResponse
	15, // 21: foodfolio.v1.CategoryService.DeleteCategory:output_type -> foodfolio.v1.SuccessResponse
	9,  // 22: foodfolio.v1.CategoryService.GetCategoryTree:output_type -> foodfolio.v1.GetCategoryTreeResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_category_proto_init() }
func file_category_proto_init() {
	if File_category_proto != nil {
		return
	}
	file_common_proto_init()
	file_category_proto_msgTypes[0].OneofWrappers = []any{}
	file_category_proto_msgTypes[1].OneofWrappers = []any{}
	file_category_proto_msgTypes[4].OneofWrappers = []any{}
	file_category_proto_msgTypes[6].OneofWrappers = []any{}
	file_category_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_proto_rawDesc), len(file_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_proto_goTypes,
		DependencyIndexes: file_category_proto_depIdxs,
		MessageInfos:      file_category_proto_msgTypes,
	}.Build()
	File_category_proto = out.File
	file_category_proto_goTypes = nil
	file_category_proto_depIdxs = nil
}
