// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: company.proto

package foodfoliov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Company (Brand/Manufacturer) message
type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Timestamps    *Timestamps            `protobuf:"bytes,4,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	ItemCount     int32                  `protobuf:"varint,5,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"` // Number of items from this company
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{0}
}

func (x *Company) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Company) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *Company) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

// Create company request
type CreateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyRequest) Reset() {
	*x = CreateCompanyRequest{}
	mi := &file_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyRequest) ProtoMessage() {}

func (x *CreateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCompanyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Create company response
type CreateCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *Company               `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCompanyResponse) Reset() {
	*x = CreateCompanyResponse{}
	mi := &file_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCompanyResponse) ProtoMessage() {}

func (x *CreateCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCompanyResponse.ProtoReflect.Descriptor instead.
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCompanyResponse) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

// Get company response
type GetCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *Company               `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyResponse) Reset() {
	*x = GetCompanyResponse{}
	mi := &file_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyResponse) ProtoMessage() {}

func (x *GetCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{3}
}

func (x *GetCompanyResponse) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

// List companies request
type ListCompaniesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *string                `protobuf:"bytes,1,opt,name=search,proto3,oneof" json:"search,omitempty"` // Search by name
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	DeletedFilter *DeletedFilter         `protobuf:"bytes,3,opt,name=deleted_filter,json=deletedFilter,proto3" json:"deleted_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompaniesRequest) Reset() {
	*x = ListCompaniesRequest{}
	mi := &file_company_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompaniesRequest) ProtoMessage() {}

func (x *ListCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompaniesRequest.ProtoReflect.Descriptor instead.
func (*ListCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{4}
}

func (x *ListCompaniesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListCompaniesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCompaniesRequest) GetDeletedFilter() *DeletedFilter {
	if x != nil {
		return x.DeletedFilter
	}
	return nil
}

// List companies response
type ListCompaniesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*Company             `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompaniesResponse) Reset() {
	*x = ListCompaniesResponse{}
	mi := &file_company_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompaniesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompaniesResponse) ProtoMessage() {}

func (x *ListCompaniesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompaniesResponse.ProtoReflect.Descriptor instead.
func (*ListCompaniesResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{5}
}

func (x *ListCompaniesResponse) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

func (x *ListCompaniesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Update company request
type UpdateCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyRequest) Reset() {
	*x = UpdateCompanyRequest{}
	mi := &file_company_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyRequest) ProtoMessage() {}

func (x *UpdateCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCompanyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCompanyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Update company response
type UpdateCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *Company               `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanyResponse) Reset() {
	*x = UpdateCompanyResponse{}
	mi := &file_company_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanyResponse) ProtoMessage() {}

func (x *UpdateCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_company_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanyResponse.ProtoReflect.Descriptor instead.
func (*UpdateCompanyResponse) Descriptor() ([]byte, []int) {
	return file_company_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCompanyResponse) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

var File_company_proto protoreflect.FileDescriptor

const file_company_proto_rawDesc = "" +
	"\n" +
	"\rcompany.proto\x12\ffoodfolio.v1\x1a\fcommon.proto\"\x9a\x01\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x128\n" +
	"\n" +
	"timestamps\x18\x04 \x01(\v2\x18.foodfolio.v1.TimestampsR\n" +
	"timestamps\x12\x1d\n" +
	"\n" +
	"item_count\x18\x05 \x01(\x05R\titemCount\"*\n" +
	"\x14CreateCompanyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x15CreateCompanyResponse\x12/\n" +
	"\acompany\x18\x01 \x01(\v2\x15.foodfolio.v1.CompanyR\acompany\"E\n" +
	"\x12GetCompanyResponse\x12/\n" +
	"\acompany\x18\x01 \x01(\v2\x15.foodfolio.v1.CompanyR\acompany\"\xc3\x01\n" +
	"\x14ListCompaniesRequest\x12\x1b\n" +
	"\x06search\x18\x01 \x01(\tH\x00R\x06search\x88\x01\x01\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.foodfolio.v1.PaginationRequestR\n" +
	"pagination\x12B\n" +
	"\x0edeleted_filter\x18\x03 \x01(\v2\x1b.foodfolio.v1.DeletedFilterR\rdeletedFilterB\t\n" +
	"\a_search\"\x8e\x01\n" +
	"\x15ListCompaniesResponse\x123\n" +
	"\tcompanies\x18\x01 \x03(\v2\x15.foodfolio.v1.CompanyR\tcompanies\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .foodfolio.v1.PaginationResponseR\n" +
	"pagination\":\n" +
	"\x14UpdateCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"H\n" +
	"\x15UpdateCompanyResponse\x12/\n" +
	"\acompany\x18\x01 \x01(\v2\x15.foodfolio.v1.CompanyR\acompany2\xb0\x03\n" +
	"\x0eCompanyService\x12X\n" +
	"\rCreateCompany\x12\".foodfolio.v1.CreateCompanyRequest\x1a#.foodfolio.v1.CreateCompanyResponse\x12G\n" +
	"\n" +
	"GetCompany\x12\x17.foodfolio.v1.IdRequest\x1a .foodfolio.v1.GetCompanyResponse\x12X\n" +
	"\rListCompanies\x12\".foodfolio.v1.ListCompaniesRequest\x1a#.foodfolio.v1.ListCompaniesResponse\x12X\n" +
	"\rUpdateCompany\x12\".foodfolio.v1.UpdateCompanyRequest\x1a#.foodfolio.v1.UpdateCompanyResponse\x12G\n" +
	"\rDeleteCompany\x12\x17.foodfolio.v1.IdRequest\x1a\x1d.foodfolio.v1.SuccessResponseBJZHtoxictoast/services/foodfolio-service/api/proto/foodfolio/v1;foodfoliov1b\x06proto3"

var (
	file_company_proto_rawDescOnce sync.Once
	file_company_proto_rawDescData []byte
)

func file_company_proto_rawDescGZIP() []byte {
	file_company_proto_rawDescOnce.Do(func() {
		file_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_company_proto_rawDesc), len(file_company_proto_rawDesc)))
	})
	return file_company_proto_rawDescData
}

var file_company_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_company_proto_goTypes = []any{
	(*Company)(nil),               // 0: foodfolio.v1.Company
	(*CreateCompanyRequest)(nil),  // 1: foodfolio.v1.CreateCompanyRequest
	(*CreateCompanyResponse)(nil), // 2: foodfolio.v1.CreateCompanyResponse
	(*GetCompanyResponse)(nil),    // 3: foodfolio.v1.GetCompanyResponse
	(*ListCompaniesRequest)(nil),  // 4: foodfolio.v1.ListCompaniesRequest
	(*ListCompaniesResponse)(nil), // 5: foodfolio.v1.ListCompaniesResponse
	(*UpdateCompanyRequest)(nil),  // 6: foodfolio.v1.UpdateCompanyRequest
	(*UpdateCompanyResponse)(nil), // 7: foodfolio.v1.UpdateCompanyResponse
	(*Timestamps)(nil),            // 8: foodfolio.v1.Timestamps
	(*PaginationRequest)(nil),     // 9: foodfolio.v1.PaginationRequest
	(*DeletedFilter)(nil),         // 10: foodfolio.v1.DeletedFilter
	(*PaginationResponse)(nil),    // 11: foodfolio.v1.PaginationResponse
	(*IdRequest)(nil),             // 12: foodfolio.v1.IdRequest
	(*SuccessResponse)(nil),       // 13: foodfolio.v1.SuccessResponse
}
var file_company_proto_depIdxs = []int32{
	8,  // 0: foodfolio.v1.Company.timestamps:type_name -> foodfolio.v1.Timestamps
	0,  // 1: foodfolio.v1.CreateCompanyResponse.company:type_name -> foodfolio.v1.Company
	0,  // 2: foodfolio.v1.GetCompanyResponse.company:type_name -> foodfolio.v1.Company
	9,  // 3: foodfolio.v1.ListCompaniesRequest.pagination:type_name -> foodfolio.v1.PaginationRequest
	10, // 4: foodfolio.v1.ListCompaniesRequest.deleted_filter:type_name -> foodfolio.v1.DeletedFilter
	0,  // 5: foodfolio.v1.ListCompaniesResponse.companies:type_name -> foodfolio.v1.Company
	11, // 6: foodfolio.v1.ListCompaniesResponse.pagination:type_name -> foodfolio.v1.PaginationResponse
	0,  // 7: foodfolio.v1.UpdateCompanyResponse.company:type_name -> foodfolio.v1.Company
	1,  // 8: foodfolio.v1.CompanyService.CreateCompany:input_type -> foodfolio.v1.CreateCompanyRequest
	12, // 9: foodfolio.v1.CompanyService.GetCompany:input_type -> foodfolio.v1.IdRequest
	4,  // 10: foodfolio.v1.CompanyService.ListCompanies:input_type -> foodfolio.v1.ListCompaniesRequest
	6,  // 11: foodfolio.v1.CompanyService.UpdateCompany:input_type -> foodfolio.v1.UpdateCompanyRequest
	12, // 12: foodfolio.v1.CompanyService.DeleteCompany:input_type -> foodfolio.v1.IdRequest
	2,  // 13: foodfolio.v1.CompanyService.CreateCompany:output_type -> foodfolio.v1.CreateCompanyResponse
	3,  // 14: foodfolio.v1.CompanyService.GetCompany:output_type -> foodfolio.v1.GetCompanyResponse
	5,  // 15: foodfolio.v1.CompanyService.ListCompanies:output_type -> foodfolio.v1.ListCompaniesResponse
	7,  // 16: foodfolio.v1.CompanyService.UpdateCompany:output_type -> foodfolio.v1.UpdateCompanyResponse
	13, // 17: foodfolio.v1.CompanyService.DeleteCompany:output_type -> foodfolio.v1.SuccessResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_company_proto_init() }
func file_company_proto_init() {
	if File_company_proto != nil {
		return
	}
	file_common_proto_init()
	file_company_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_company_proto_rawDesc), len(file_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_company_proto_goTypes,
		DependencyIndexes: file_company_proto_depIdxs,
		MessageInfos:      file_company_proto_msgTypes,
	}.Build()
	File_company_proto = out.File
	file_company_proto_goTypes = nil
	file_company_proto_depIdxs = nil
}
