// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: item_variant.proto

package foodfoliov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemVariantService_CreateItemVariant_FullMethodName      = "/foodfolio.v1.ItemVariantService/CreateItemVariant"
	ItemVariantService_GetItemVariant_FullMethodName         = "/foodfolio.v1.ItemVariantService/GetItemVariant"
	ItemVariantService_ListItemVariants_FullMethodName       = "/foodfolio.v1.ItemVariantService/ListItemVariants"
	ItemVariantService_UpdateItemVariant_FullMethodName      = "/foodfolio.v1.ItemVariantService/UpdateItemVariant"
	ItemVariantService_DeleteItemVariant_FullMethodName      = "/foodfolio.v1.ItemVariantService/DeleteItemVariant"
	ItemVariantService_GetCurrentStock_FullMethodName        = "/foodfolio.v1.ItemVariantService/GetCurrentStock"
	ItemVariantService_GetLowStockVariants_FullMethodName    = "/foodfolio.v1.ItemVariantService/GetLowStockVariants"
	ItemVariantService_GetOverstockedVariants_FullMethodName = "/foodfolio.v1.ItemVariantService/GetOverstockedVariants"
	ItemVariantService_GetItemWithVariants_FullMethodName    = "/foodfolio.v1.ItemVariantService/GetItemWithVariants"
	ItemVariantService_ScanBarcode_FullMethodName            = "/foodfolio.v1.ItemVariantService/ScanBarcode"
)

// ItemVariantServiceClient is the client API for ItemVariantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemVariant service
type ItemVariantServiceClient interface {
	CreateItemVariant(ctx context.Context, in *CreateItemVariantRequest, opts ...grpc.CallOption) (*CreateItemVariantResponse, error)
	GetItemVariant(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GetItemVariantResponse, error)
	ListItemVariants(ctx context.Context, in *ListItemVariantsRequest, opts ...grpc.CallOption) (*ListItemVariantsResponse, error)
	UpdateItemVariant(ctx context.Context, in *UpdateItemVariantRequest, opts ...grpc.CallOption) (*UpdateItemVariantResponse, error)
	DeleteItemVariant(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	// Stock management
	GetCurrentStock(ctx context.Context, in *GetCurrentStockRequest, opts ...grpc.CallOption) (*GetCurrentStockResponse, error)
	GetLowStockVariants(ctx context.Context, in *GetLowStockVariantsRequest, opts ...grpc.CallOption) (*GetLowStockVariantsResponse, error)
	GetOverstockedVariants(ctx context.Context, in *GetOverstockedVariantsRequest, opts ...grpc.CallOption) (*GetOverstockedVariantsResponse, error)
	GetItemWithVariants(ctx context.Context, in *GetItemWithVariantsRequest, opts ...grpc.CallOption) (*GetItemWithVariantsResponse, error)
	// Barcode
	ScanBarcode(ctx context.Context, in *ScanBarcodeRequest, opts ...grpc.CallOption) (*ScanBarcodeResponse, error)
}

type itemVariantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemVariantServiceClient(cc grpc.ClientConnInterface) ItemVariantServiceClient {
	return &itemVariantServiceClient{cc}
}

func (c *itemVariantServiceClient) CreateItemVariant(ctx context.Context, in *CreateItemVariantRequest, opts ...grpc.CallOption) (*CreateItemVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateItemVariantResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_CreateItemVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) GetItemVariant(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GetItemVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemVariantResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_GetItemVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) ListItemVariants(ctx context.Context, in *ListItemVariantsRequest, opts ...grpc.CallOption) (*ListItemVariantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemVariantsResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_ListItemVariants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) UpdateItemVariant(ctx context.Context, in *UpdateItemVariantRequest, opts ...grpc.CallOption) (*UpdateItemVariantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateItemVariantResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_UpdateItemVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) DeleteItemVariant(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_DeleteItemVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) GetCurrentStock(ctx context.Context, in *GetCurrentStockRequest, opts ...grpc.CallOption) (*GetCurrentStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentStockResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_GetCurrentStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) GetLowStockVariants(ctx context.Context, in *GetLowStockVariantsRequest, opts ...grpc.CallOption) (*GetLowStockVariantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLowStockVariantsResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_GetLowStockVariants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) GetOverstockedVariants(ctx context.Context, in *GetOverstockedVariantsRequest, opts ...grpc.CallOption) (*GetOverstockedVariantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOverstockedVariantsResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_GetOverstockedVariants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) GetItemWithVariants(ctx context.Context, in *GetItemWithVariantsRequest, opts ...grpc.CallOption) (*GetItemWithVariantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemWithVariantsResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_GetItemWithVariants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemVariantServiceClient) ScanBarcode(ctx context.Context, in *ScanBarcodeRequest, opts ...grpc.CallOption) (*ScanBarcodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanBarcodeResponse)
	err := c.cc.Invoke(ctx, ItemVariantService_ScanBarcode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemVariantServiceServer is the server API for ItemVariantService service.
// All implementations must embed UnimplementedItemVariantServiceServer
// for forward compatibility.
//
// ItemVariant service
type ItemVariantServiceServer interface {
	CreateItemVariant(context.Context, *CreateItemVariantRequest) (*CreateItemVariantResponse, error)
	GetItemVariant(context.Context, *IdRequest) (*GetItemVariantResponse, error)
	ListItemVariants(context.Context, *ListItemVariantsRequest) (*ListItemVariantsResponse, error)
	UpdateItemVariant(context.Context, *UpdateItemVariantRequest) (*UpdateItemVariantResponse, error)
	DeleteItemVariant(context.Context, *IdRequest) (*SuccessResponse, error)
	// Stock management
	GetCurrentStock(context.Context, *GetCurrentStockRequest) (*GetCurrentStockResponse, error)
	GetLowStockVariants(context.Context, *GetLowStockVariantsRequest) (*GetLowStockVariantsResponse, error)
	GetOverstockedVariants(context.Context, *GetOverstockedVariantsRequest) (*GetOverstockedVariantsResponse, error)
	GetItemWithVariants(context.Context, *GetItemWithVariantsRequest) (*GetItemWithVariantsResponse, error)
	// Barcode
	ScanBarcode(context.Context, *ScanBarcodeRequest) (*ScanBarcodeResponse, error)
	mustEmbedUnimplementedItemVariantServiceServer()
}

// UnimplementedItemVariantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemVariantServiceServer struct{}

func (UnimplementedItemVariantServiceServer) CreateItemVariant(context.Context, *CreateItemVariantRequest) (*CreateItemVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItemVariant not implemented")
}
func (UnimplementedItemVariantServiceServer) GetItemVariant(context.Context, *IdRequest) (*GetItemVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemVariant not implemented")
}
func (UnimplementedItemVariantServiceServer) ListItemVariants(context.Context, *ListItemVariantsRequest) (*ListItemVariantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItemVariants not implemented")
}
func (UnimplementedItemVariantServiceServer) UpdateItemVariant(context.Context, *UpdateItemVariantRequest) (*UpdateItemVariantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItemVariant not implemented")
}
func (UnimplementedItemVariantServiceServer) DeleteItemVariant(context.Context, *IdRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItemVariant not implemented")
}
func (UnimplementedItemVariantServiceServer) GetCurrentStock(context.Context, *GetCurrentStockRequest) (*GetCurrentStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentStock not implemented")
}
func (UnimplementedItemVariantServiceServer) GetLowStockVariants(context.Context, *GetLowStockVariantsRequest) (*GetLowStockVariantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLowStockVariants not implemented")
}
func (UnimplementedItemVariantServiceServer) GetOverstockedVariants(context.Context, *GetOverstockedVariantsRequest) (*GetOverstockedVariantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOverstockedVariants not implemented")
}
func (UnimplementedItemVariantServiceServer) GetItemWithVariants(context.Context, *GetItemWithVariantsRequest) (*GetItemWithVariantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemWithVariants not implemented")
}
func (UnimplementedItemVariantServiceServer) ScanBarcode(context.Context, *ScanBarcodeRequest) (*ScanBarcodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanBarcode not implemented")
}
func (UnimplementedItemVariantServiceServer) mustEmbedUnimplementedItemVariantServiceServer() {}
func (UnimplementedItemVariantServiceServer) testEmbeddedByValue()                            {}

// UnsafeItemVariantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemVariantServiceServer will
// result in compilation errors.
type UnsafeItemVariantServiceServer interface {
	mustEmbedUnimplementedItemVariantServiceServer()
}

func RegisterItemVariantServiceServer(s grpc.ServiceRegistrar, srv ItemVariantServiceServer) {
	// If the following call pancis, it indicates UnimplementedItemVariantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemVariantService_ServiceDesc, srv)
}

func _ItemVariantService_CreateItemVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).CreateItemVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_CreateItemVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).CreateItemVariant(ctx, req.(*CreateItemVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_GetItemVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).GetItemVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_GetItemVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).GetItemVariant(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_ListItemVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemVariantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).ListItemVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_ListItemVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).ListItemVariants(ctx, req.(*ListItemVariantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_UpdateItemVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemVariantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).UpdateItemVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_UpdateItemVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).UpdateItemVariant(ctx, req.(*UpdateItemVariantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_DeleteItemVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).DeleteItemVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_DeleteItemVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).DeleteItemVariant(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_GetCurrentStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).GetCurrentStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_GetCurrentStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).GetCurrentStock(ctx, req.(*GetCurrentStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_GetLowStockVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLowStockVariantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).GetLowStockVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_GetLowStockVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).GetLowStockVariants(ctx, req.(*GetLowStockVariantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_GetOverstockedVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverstockedVariantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).GetOverstockedVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_GetOverstockedVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).GetOverstockedVariants(ctx, req.(*GetOverstockedVariantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_GetItemWithVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemWithVariantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).GetItemWithVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_GetItemWithVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).GetItemWithVariants(ctx, req.(*GetItemWithVariantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemVariantService_ScanBarcode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanBarcodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemVariantServiceServer).ScanBarcode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemVariantService_ScanBarcode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemVariantServiceServer).ScanBarcode(ctx, req.(*ScanBarcodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemVariantService_ServiceDesc is the grpc.ServiceDesc for ItemVariantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemVariantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foodfolio.v1.ItemVariantService",
	HandlerType: (*ItemVariantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItemVariant",
			Handler:    _ItemVariantService_CreateItemVariant_Handler,
		},
		{
			MethodName: "GetItemVariant",
			Handler:    _ItemVariantService_GetItemVariant_Handler,
		},
		{
			MethodName: "ListItemVariants",
			Handler:    _ItemVariantService_ListItemVariants_Handler,
		},
		{
			MethodName: "UpdateItemVariant",
			Handler:    _ItemVariantService_UpdateItemVariant_Handler,
		},
		{
			MethodName: "DeleteItemVariant",
			Handler:    _ItemVariantService_DeleteItemVariant_Handler,
		},
		{
			MethodName: "GetCurrentStock",
			Handler:    _ItemVariantService_GetCurrentStock_Handler,
		},
		{
			MethodName: "GetLowStockVariants",
			Handler:    _ItemVariantService_GetLowStockVariants_Handler,
		},
		{
			MethodName: "GetOverstockedVariants",
			Handler:    _ItemVariantService_GetOverstockedVariants_Handler,
		},
		{
			MethodName: "GetItemWithVariants",
			Handler:    _ItemVariantService_GetItemWithVariants_Handler,
		},
		{
			MethodName: "ScanBarcode",
			Handler:    _ItemVariantService_ScanBarcode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_variant.proto",
}
