// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: location.proto

package foodfoliov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location (Storage Location) message
type Location struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // "Kühlschrank", "Vorratsschrank", "Gefrierschrank"
	Slug       string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ParentId   *string                `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"` // e.g., "Fridge" -> "Top Shelf"
	Timestamps *Timestamps            `protobuf:"bytes,5,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	// Optional relations
	Parent        *Location   `protobuf:"bytes,6,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	Children      []*Location `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	ItemCount     int32       `protobuf:"varint,8,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"` // Number of items stored here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Location) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Location) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *Location) GetParent() *Location {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Location) GetChildren() []*Location {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Location) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

// Create location request
type CreateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationRequest) Reset() {
	*x = CreateLocationRequest{}
	mi := &file_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationRequest) ProtoMessage() {}

func (x *CreateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationRequest.ProtoReflect.Descriptor instead.
func (*CreateLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLocationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLocationRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

// Create location response
type CreateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationResponse) Reset() {
	*x = CreateLocationResponse{}
	mi := &file_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationResponse) ProtoMessage() {}

func (x *CreateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationResponse.ProtoReflect.Descriptor instead.
func (*CreateLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Get location response
type GetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// List locations request
type ListLocationsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentId        *string                `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`                 // Filter by parent (null = root locations)
	IncludeChildren bool                   `protobuf:"varint,2,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"` // Include children in response
	Pagination      *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	DeletedFilter   *DeletedFilter         `protobuf:"bytes,4,opt,name=deleted_filter,json=deletedFilter,proto3" json:"deleted_filter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListLocationsRequest) Reset() {
	*x = ListLocationsRequest{}
	mi := &file_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsRequest) ProtoMessage() {}

func (x *ListLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{4}
}

func (x *ListLocationsRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *ListLocationsRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

func (x *ListLocationsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListLocationsRequest) GetDeletedFilter() *DeletedFilter {
	if x != nil {
		return x.DeletedFilter
	}
	return nil
}

// List locations response
type ListLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsResponse) Reset() {
	*x = ListLocationsResponse{}
	mi := &file_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResponse) ProtoMessage() {}

func (x *ListLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{5}
}

func (x *ListLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *ListLocationsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Update location request
type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ParentId      *string                `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"` // Set to empty string to remove parent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLocationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateLocationRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

// Update location response
type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Get location tree request
type GetLocationTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        *string                `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3,oneof" json:"root_id,omitempty"`  // Start from specific location, or null for full tree
	MaxDepth      int32                  `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // Maximum depth to fetch (0 = unlimited)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationTreeRequest) Reset() {
	*x = GetLocationTreeRequest{}
	mi := &file_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationTreeRequest) ProtoMessage() {}

func (x *GetLocationTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationTreeRequest.ProtoReflect.Descriptor instead.
func (*GetLocationTreeRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{8}
}

func (x *GetLocationTreeRequest) GetRootId() string {
	if x != nil && x.RootId != nil {
		return *x.RootId
	}
	return ""
}

func (x *GetLocationTreeRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// Get location tree response
type GetLocationTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"` // Root locations with nested children
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationTreeResponse) Reset() {
	*x = GetLocationTreeResponse{}
	mi := &file_location_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationTreeResponse) ProtoMessage() {}

func (x *GetLocationTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationTreeResponse.ProtoReflect.Descriptor instead.
func (*GetLocationTreeResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{9}
}

func (x *GetLocationTreeResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_location_proto protoreflect.FileDescriptor

const file_location_proto_rawDesc = "" +
	"\n" +
	"\x0elocation.proto\x12\ffoodfolio.v1\x1a\fcommon.proto\"\xbf\x02\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x00R\bparentId\x88\x01\x01\x128\n" +
	"\n" +
	"timestamps\x18\x05 \x01(\v2\x18.foodfolio.v1.TimestampsR\n" +
	"timestamps\x123\n" +
	"\x06parent\x18\x06 \x01(\v2\x16.foodfolio.v1.LocationH\x01R\x06parent\x88\x01\x01\x122\n" +
	"\bchildren\x18\a \x03(\v2\x16.foodfolio.v1.LocationR\bchildren\x12\x1d\n" +
	"\n" +
	"item_count\x18\b \x01(\x05R\titemCountB\f\n" +
	"\n" +
	"_parent_idB\t\n" +
	"\a_parent\"[\n" +
	"\x15CreateLocationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"L\n" +
	"\x16CreateLocationResponse\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.foodfolio.v1.LocationR\blocation\"I\n" +
	"\x13GetLocationResponse\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.foodfolio.v1.LocationR\blocation\"\xf6\x01\n" +
	"\x14ListLocationsRequest\x12 \n" +
	"\tparent_id\x18\x01 \x01(\tH\x00R\bparentId\x88\x01\x01\x12)\n" +
	"\x10include_children\x18\x02 \x01(\bR\x0fincludeChildren\x12?\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1f.foodfolio.v1.PaginationRequestR\n" +
	"pagination\x12B\n" +
	"\x0edeleted_filter\x18\x04 \x01(\v2\x1b.foodfolio.v1.DeletedFilterR\rdeletedFilterB\f\n" +
	"\n" +
	"_parent_id\"\x8f\x01\n" +
	"\x15ListLocationsResponse\x124\n" +
	"\tlocations\x18\x01 \x03(\v2\x16.foodfolio.v1.LocationR\tlocations\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .foodfolio.v1.PaginationResponseR\n" +
	"pagination\"y\n" +
	"\x15UpdateLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\tH\x01R\bparentId\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_parent_id\"L\n" +
	"\x16UpdateLocationResponse\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.foodfolio.v1.LocationR\blocation\"_\n" +
	"\x16GetLocationTreeRequest\x12\x1c\n" +
	"\aroot_id\x18\x01 \x01(\tH\x00R\x06rootId\x88\x01\x01\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepthB\n" +
	"\n" +
	"\b_root_id\"O\n" +
	"\x17GetLocationTreeResponse\x124\n" +
	"\tlocations\x18\x01 \x03(\v2\x16.foodfolio.v1.LocationR\tlocations2\x9a\x04\n" +
	"\x0fLocationService\x12[\n" +
	"\x0eCreateLocation\x12#.foodfolio.v1.CreateLocationRequest\x1a$.foodfolio.v1.CreateLocationResponse\x12I\n" +
	"\vGetLocation\x12\x17.foodfolio.v1.IdRequest\x1a!.foodfolio.v1.GetLocationResponse\x12X\n" +
	"\rListLocations\x12\".foodfolio.v1.ListLocationsRequest\x1a#.foodfolio.v1.ListLocationsResponse\x12[\n" +
	"\x0eUpdateLocation\x12#.foodfolio.v1.UpdateLocationRequest\x1a$.foodfolio.v1.UpdateLocationResponse\x12H\n" +
	"\x0eDeleteLocation\x12\x17.foodfolio.v1.IdRequest\x1a\x1d.foodfolio.v1.SuccessResponse\x12^\n" +
	"\x0fGetLocationTree\x12$.foodfolio.v1.GetLocationTreeRequest\x1a%.foodfolio.v1.GetLocationTreeResponseBJZHtoxictoast/services/foodfolio-service/api/proto/foodfolio/v1;foodfoliov1b\x06proto3"

var (
	file_location_proto_rawDescOnce sync.Once
	file_location_proto_rawDescData []byte
)

func file_location_proto_rawDescGZIP() []byte {
	file_location_proto_rawDescOnce.Do(func() {
		file_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)))
	})
	return file_location_proto_rawDescData
}

var file_location_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_location_proto_goTypes = []any{
	(*Location)(nil),                // 0: foodfolio.v1.Location
	(*CreateLocationRequest)(nil),   // 1: foodfolio.v1.CreateLocationRequest
	(*CreateLocationResponse)(nil),  // 2: foodfolio.v1.CreateLocationResponse
	(*GetLocationResponse)(nil),     // 3: foodfolio.v1.GetLocationResponse
	(*ListLocationsRequest)(nil),    // 4: foodfolio.v1.ListLocationsRequest
	(*ListLocationsResponse)(nil),   // 5: foodfolio.v1.ListLocationsResponse
	(*UpdateLocationRequest)(nil),   // 6: foodfolio.v1.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),  // 7: foodfolio.v1.UpdateLocationResponse
	(*GetLocationTreeRequest)(nil),  // 8: foodfolio.v1.GetLocationTreeRequest
	(*GetLocationTreeResponse)(nil), // 9: foodfolio.v1.GetLocationTreeResponse
	(*Timestamps)(nil),              // 10: foodfolio.v1.Timestamps
	(*PaginationRequest)(nil),       // 11: foodfolio.v1.PaginationRequest
	(*DeletedFilter)(nil),           // 12: foodfolio.v1.DeletedFilter
	(*PaginationResponse)(nil),      // 13: foodfolio.v1.PaginationResponse
	(*IdRequest)(nil),               // 14: foodfolio.v1.IdRequest
	(*SuccessResponse)(nil),         // 15: foodfolio.v1.SuccessResponse
}
var file_location_proto_depIdxs = []int32{
	10, // 0: foodfolio.v1.Location.timestamps:type_name -> foodfolio.v1.Timestamps
	0,  // 1: foodfolio.v1.Location.parent:type_name -> foodfolio.v1.Location
	0,  // 2: foodfolio.v1.Location.children:type_name -> foodfolio.v1.Location
	0,  // 3: foodfolio.v1.CreateLocationResponse.location:type_name -> foodfolio.v1.Location
	0,  // 4: foodfolio.v1.GetLocationResponse.location:type_name -> foodfolio.v1.Location
	11, // 5: foodfolio.v1.ListLocationsRequest.pagination:type_name -> foodfolio.v1.PaginationRequest
	12, // 6: foodfolio.v1.ListLocationsRequest.deleted_filter:type_name -> foodfolio.v1.DeletedFilter
	0,  // 7: foodfolio.v1.ListLocationsResponse.locations:type_name -> foodfolio.v1.Location
	13, // 8: foodfolio.v1.ListLocationsResponse.pagination:type_name -> foodfolio.v1.PaginationResponse
	0,  // 9: foodfolio.v1.UpdateLocationResponse.location:type_name -> foodfolio.v1.Location
	0,  // 10: foodfolio.v1.GetLocationTreeResponse.locations:type_name -> foodfolio.v1.Location
	1,  // 11: foodfolio.v1.LocationService.CreateLocation:input_type -> foodfolio.v1.CreateLocationRequest
	14, // 12: foodfolio.v1.LocationService.GetLocation:input_type -> foodfolio.v1.IdRequest
	4,  // 13: foodfolio.v1.LocationService.ListLocations:input_type -> foodfolio.v1.ListLocationsRequest
	6,  // 14: foodfolio.v1.LocationService.UpdateLocation:input_type -> foodfolio.v1.UpdateLocationRequest
	14, // 15: foodfolio.v1.LocationService.DeleteLocation:input_type -> foodfolio.v1.IdRequest
	8,  // 16: foodfolio.v1.LocationService.GetLocationTree:input_type -> foodfolio.v1.GetLocationTreeRequest
	2,  // 17: foodfolio.v1.LocationService.CreateLocation:output_type -> foodfolio.v1.CreateLocationResponse
	3,  // 18: foodfolio.v1.LocationService.GetLocation:output_type -> foodfolio.v1.GetLocationResponse
	5,  // 19: foodfolio.v1.LocationService.ListLocations:output_type -> foodfolio.v1.ListLocationsResponse
	7,  // 20: foodfolio.v1.LocationService.UpdateLocation:output_type -> foodfolio.v1.UpdateLocationResponse
	15, // 21: foodfolio.v1.LocationService.DeleteLocation:output_type -> foodfolio.v1.SuccessResponse
	9,  // 22: foodfolio.v1.LocationService.GetLocationTree:output_type -> foodfolio.v1.GetLocationTreeResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_location_proto_init() }
func file_location_proto_init() {
	if File_location_proto != nil {
		return
	}
	file_common_proto_init()
	file_location_proto_msgTypes[0].OneofWrappers = []any{}
	file_location_proto_msgTypes[1].OneofWrappers = []any{}
	file_location_proto_msgTypes[4].OneofWrappers = []any{}
	file_location_proto_msgTypes[6].OneofWrappers = []any{}
	file_location_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_proto_goTypes,
		DependencyIndexes: file_location_proto_depIdxs,
		MessageInfos:      file_location_proto_msgTypes,
	}.Build()
	File_location_proto = out.File
	file_location_proto_goTypes = nil
	file_location_proto_depIdxs = nil
}
