// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: size.proto

package foodfoliov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SizeService_CreateSize_FullMethodName = "/foodfolio.v1.SizeService/CreateSize"
	SizeService_GetSize_FullMethodName    = "/foodfolio.v1.SizeService/GetSize"
	SizeService_ListSizes_FullMethodName  = "/foodfolio.v1.SizeService/ListSizes"
	SizeService_UpdateSize_FullMethodName = "/foodfolio.v1.SizeService/UpdateSize"
	SizeService_DeleteSize_FullMethodName = "/foodfolio.v1.SizeService/DeleteSize"
)

// SizeServiceClient is the client API for SizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Size service
type SizeServiceClient interface {
	CreateSize(ctx context.Context, in *CreateSizeRequest, opts ...grpc.CallOption) (*CreateSizeResponse, error)
	GetSize(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GetSizeResponse, error)
	ListSizes(ctx context.Context, in *ListSizesRequest, opts ...grpc.CallOption) (*ListSizesResponse, error)
	UpdateSize(ctx context.Context, in *UpdateSizeRequest, opts ...grpc.CallOption) (*UpdateSizeResponse, error)
	DeleteSize(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type sizeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSizeServiceClient(cc grpc.ClientConnInterface) SizeServiceClient {
	return &sizeServiceClient{cc}
}

func (c *sizeServiceClient) CreateSize(ctx context.Context, in *CreateSizeRequest, opts ...grpc.CallOption) (*CreateSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSizeResponse)
	err := c.cc.Invoke(ctx, SizeService_CreateSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) GetSize(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*GetSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSizeResponse)
	err := c.cc.Invoke(ctx, SizeService_GetSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) ListSizes(ctx context.Context, in *ListSizesRequest, opts ...grpc.CallOption) (*ListSizesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSizesResponse)
	err := c.cc.Invoke(ctx, SizeService_ListSizes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) UpdateSize(ctx context.Context, in *UpdateSizeRequest, opts ...grpc.CallOption) (*UpdateSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSizeResponse)
	err := c.cc.Invoke(ctx, SizeService_UpdateSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) DeleteSize(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, SizeService_DeleteSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SizeServiceServer is the server API for SizeService service.
// All implementations must embed UnimplementedSizeServiceServer
// for forward compatibility.
//
// Size service
type SizeServiceServer interface {
	CreateSize(context.Context, *CreateSizeRequest) (*CreateSizeResponse, error)
	GetSize(context.Context, *IdRequest) (*GetSizeResponse, error)
	ListSizes(context.Context, *ListSizesRequest) (*ListSizesResponse, error)
	UpdateSize(context.Context, *UpdateSizeRequest) (*UpdateSizeResponse, error)
	DeleteSize(context.Context, *IdRequest) (*SuccessResponse, error)
	mustEmbedUnimplementedSizeServiceServer()
}

// UnimplementedSizeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSizeServiceServer struct{}

func (UnimplementedSizeServiceServer) CreateSize(context.Context, *CreateSizeRequest) (*CreateSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSize not implemented")
}
func (UnimplementedSizeServiceServer) GetSize(context.Context, *IdRequest) (*GetSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSize not implemented")
}
func (UnimplementedSizeServiceServer) ListSizes(context.Context, *ListSizesRequest) (*ListSizesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSizes not implemented")
}
func (UnimplementedSizeServiceServer) UpdateSize(context.Context, *UpdateSizeRequest) (*UpdateSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSize not implemented")
}
func (UnimplementedSizeServiceServer) DeleteSize(context.Context, *IdRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSize not implemented")
}
func (UnimplementedSizeServiceServer) mustEmbedUnimplementedSizeServiceServer() {}
func (UnimplementedSizeServiceServer) testEmbeddedByValue()                     {}

// UnsafeSizeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SizeServiceServer will
// result in compilation errors.
type UnsafeSizeServiceServer interface {
	mustEmbedUnimplementedSizeServiceServer()
}

func RegisterSizeServiceServer(s grpc.ServiceRegistrar, srv SizeServiceServer) {
	// If the following call pancis, it indicates UnimplementedSizeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SizeService_ServiceDesc, srv)
}

func _SizeService_CreateSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).CreateSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SizeService_CreateSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).CreateSize(ctx, req.(*CreateSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_GetSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).GetSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SizeService_GetSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).GetSize(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_ListSizes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSizesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).ListSizes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SizeService_ListSizes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).ListSizes(ctx, req.(*ListSizesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_UpdateSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).UpdateSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SizeService_UpdateSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).UpdateSize(ctx, req.(*UpdateSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_DeleteSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).DeleteSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SizeService_DeleteSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).DeleteSize(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SizeService_ServiceDesc is the grpc.ServiceDesc for SizeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SizeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foodfolio.v1.SizeService",
	HandlerType: (*SizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSize",
			Handler:    _SizeService_CreateSize_Handler,
		},
		{
			MethodName: "GetSize",
			Handler:    _SizeService_GetSize_Handler,
		},
		{
			MethodName: "ListSizes",
			Handler:    _SizeService_ListSizes_Handler,
		},
		{
			MethodName: "UpdateSize",
			Handler:    _SizeService_UpdateSize_Handler,
		},
		{
			MethodName: "DeleteSize",
			Handler:    _SizeService_DeleteSize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "size.proto",
}
