// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: size.proto

package foodfoliov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Size message
type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     // "500ml", "1L", "250g"
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"` // Numeric value: 500, 1, 250
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`     // Unit: "ml", "L", "g", "kg"
	Timestamps    *Timestamps            `protobuf:"bytes,5,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	VariantCount  int32                  `protobuf:"varint,6,opt,name=variant_count,json=variantCount,proto3" json:"variant_count,omitempty"` // Number of variants with this size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_size_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_size_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_size_proto_rawDescGZIP(), []int{0}
}

func (x *Size) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Size) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Size) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Size) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Size) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *Size) GetVariantCount() int32 {
	if x != nil {
		return x.VariantCount
	}
	return 0
}

// Create size request
type CreateSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSizeRequest) Reset() {
	*x = CreateSizeRequest{}
	mi := &file_size_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSizeRequest) ProtoMessage() {}

func (x *CreateSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_size_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSizeRequest.ProtoReflect.Descriptor instead.
func (*CreateSizeRequest) Descriptor() ([]byte, []int) {
	return file_size_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSizeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSizeRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateSizeRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// Create size response
type CreateSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          *Size                  `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSizeResponse) Reset() {
	*x = CreateSizeResponse{}
	mi := &file_size_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSizeResponse) ProtoMessage() {}

func (x *CreateSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_size_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSizeResponse.ProtoReflect.Descriptor instead.
func (*CreateSizeResponse) Descriptor() ([]byte, []int) {
	return file_size_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSizeResponse) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

// Get size response
type GetSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          *Size                  `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSizeResponse) Reset() {
	*x = GetSizeResponse{}
	mi := &file_size_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSizeResponse) ProtoMessage() {}

func (x *GetSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_size_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSizeResponse.ProtoReflect.Descriptor instead.
func (*GetSizeResponse) Descriptor() ([]byte, []int) {
	return file_size_proto_rawDescGZIP(), []int{3}
}

func (x *GetSizeResponse) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

// List sizes request
type ListSizesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          *string                `protobuf:"bytes,1,opt,name=unit,proto3,oneof" json:"unit,omitempty"`                           // Filter by unit
	MinValue      *float64               `protobuf:"fixed64,2,opt,name=min_value,json=minValue,proto3,oneof" json:"min_value,omitempty"` // Minimum value
	MaxValue      *float64               `protobuf:"fixed64,3,opt,name=max_value,json=maxValue,proto3,oneof" json:"max_value,omitempty"` // Maximum value
	Pagination    *PaginationRequest     `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	DeletedFilter *DeletedFilter         `protobuf:"bytes,5,opt,name=deleted_filter,json=deletedFilter,proto3" json:"deleted_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSizesRequest) Reset() {
	*x = ListSizesRequest{}
	mi := &file_size_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSizesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSizesRequest) ProtoMessage() {}

func (x *ListSizesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_size_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSizesRequest.ProtoReflect.Descriptor instead.
func (*ListSizesRequest) Descriptor() ([]byte, []int) {
	return file_size_proto_rawDescGZIP(), []int{4}
}

func (x *ListSizesRequest) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *ListSizesRequest) GetMinValue() float64 {
	if x != nil && x.MinValue != nil {
		return *x.MinValue
	}
	return 0
}

func (x *ListSizesRequest) GetMaxValue() float64 {
	if x != nil && x.MaxValue != nil {
		return *x.MaxValue
	}
	return 0
}

func (x *ListSizesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListSizesRequest) GetDeletedFilter() *DeletedFilter {
	if x != nil {
		return x.DeletedFilter
	}
	return nil
}

// List sizes response
type ListSizesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sizes         []*Size                `protobuf:"bytes,1,rep,name=sizes,proto3" json:"sizes,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSizesResponse) Reset() {
	*x = ListSizesResponse{}
	mi := &file_size_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSizesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSizesResponse) ProtoMessage() {}

func (x *ListSizesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_size_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSizesResponse.ProtoReflect.Descriptor instead.
func (*ListSizesResponse) Descriptor() ([]byte, []int) {
	return file_size_proto_rawDescGZIP(), []int{5}
}

func (x *ListSizesResponse) GetSizes() []*Size {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *ListSizesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Update size request
type UpdateSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Value         *float64               `protobuf:"fixed64,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Unit          *string                `protobuf:"bytes,4,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSizeRequest) Reset() {
	*x = UpdateSizeRequest{}
	mi := &file_size_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSizeRequest) ProtoMessage() {}

func (x *UpdateSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_size_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSizeRequest.ProtoReflect.Descriptor instead.
func (*UpdateSizeRequest) Descriptor() ([]byte, []int) {
	return file_size_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSizeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSizeRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateSizeRequest) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *UpdateSizeRequest) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

// Update size response
type UpdateSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          *Size                  `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSizeResponse) Reset() {
	*x = UpdateSizeResponse{}
	mi := &file_size_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSizeResponse) ProtoMessage() {}

func (x *UpdateSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_size_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSizeResponse.ProtoReflect.Descriptor instead.
func (*UpdateSizeResponse) Descriptor() ([]byte, []int) {
	return file_size_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSizeResponse) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

var File_size_proto protoreflect.FileDescriptor

const file_size_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"size.proto\x12\ffoodfolio.v1\x1a\fcommon.proto\"\xb3\x01\n" +
	"\x04Size\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x128\n" +
	"\n" +
	"timestamps\x18\x05 \x01(\v2\x18.foodfolio.v1.TimestampsR\n" +
	"timestamps\x12#\n" +
	"\rvariant_count\x18\x06 \x01(\x05R\fvariantCount\"Q\n" +
	"\x11CreateSizeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"<\n" +
	"\x12CreateSizeResponse\x12&\n" +
	"\x04size\x18\x01 \x01(\v2\x12.foodfolio.v1.SizeR\x04size\"9\n" +
	"\x0fGetSizeResponse\x12&\n" +
	"\x04size\x18\x01 \x01(\v2\x12.foodfolio.v1.SizeR\x04size\"\x99\x02\n" +
	"\x10ListSizesRequest\x12\x17\n" +
	"\x04unit\x18\x01 \x01(\tH\x00R\x04unit\x88\x01\x01\x12 \n" +
	"\tmin_value\x18\x02 \x01(\x01H\x01R\bminValue\x88\x01\x01\x12 \n" +
	"\tmax_value\x18\x03 \x01(\x01H\x02R\bmaxValue\x88\x01\x01\x12?\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1f.foodfolio.v1.PaginationRequestR\n" +
	"pagination\x12B\n" +
	"\x0edeleted_filter\x18\x05 \x01(\v2\x1b.foodfolio.v1.DeletedFilterR\rdeletedFilterB\a\n" +
	"\x05_unitB\f\n" +
	"\n" +
	"_min_valueB\f\n" +
	"\n" +
	"_max_value\"\x7f\n" +
	"\x11ListSizesResponse\x12(\n" +
	"\x05sizes\x18\x01 \x03(\v2\x12.foodfolio.v1.SizeR\x05sizes\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .foodfolio.v1.PaginationResponseR\n" +
	"pagination\"\x8c\x01\n" +
	"\x11UpdateSizeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x03 \x01(\x01H\x01R\x05value\x88\x01\x01\x12\x17\n" +
	"\x04unit\x18\x04 \x01(\tH\x02R\x04unit\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_valueB\a\n" +
	"\x05_unit\"<\n" +
	"\x12UpdateSizeResponse\x12&\n" +
	"\x04size\x18\x01 \x01(\v2\x12.foodfolio.v1.SizeR\x04size2\x86\x03\n" +
	"\vSizeService\x12O\n" +
	"\n" +
	"CreateSize\x12\x1f.foodfolio.v1.CreateSizeRequest\x1a .foodfolio.v1.CreateSizeResponse\x12A\n" +
	"\aGetSize\x12\x17.foodfolio.v1.IdRequest\x1a\x1d.foodfolio.v1.GetSizeResponse\x12L\n" +
	"\tListSizes\x12\x1e.foodfolio.v1.ListSizesRequest\x1a\x1f.foodfolio.v1.ListSizesResponse\x12O\n" +
	"\n" +
	"UpdateSize\x12\x1f.foodfolio.v1.UpdateSizeRequest\x1a .foodfolio.v1.UpdateSizeResponse\x12D\n" +
	"\n" +
	"DeleteSize\x12\x17.foodfolio.v1.IdRequest\x1a\x1d.foodfolio.v1.SuccessResponseBJZHtoxictoast/services/foodfolio-service/api/proto/foodfolio/v1;foodfoliov1b\x06proto3"

var (
	file_size_proto_rawDescOnce sync.Once
	file_size_proto_rawDescData []byte
)

func file_size_proto_rawDescGZIP() []byte {
	file_size_proto_rawDescOnce.Do(func() {
		file_size_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_size_proto_rawDesc), len(file_size_proto_rawDesc)))
	})
	return file_size_proto_rawDescData
}

var file_size_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_size_proto_goTypes = []any{
	(*Size)(nil),               // 0: foodfolio.v1.Size
	(*CreateSizeRequest)(nil),  // 1: foodfolio.v1.CreateSizeRequest
	(*CreateSizeResponse)(nil), // 2: foodfolio.v1.CreateSizeResponse
	(*GetSizeResponse)(nil),    // 3: foodfolio.v1.GetSizeResponse
	(*ListSizesRequest)(nil),   // 4: foodfolio.v1.ListSizesRequest
	(*ListSizesResponse)(nil),  // 5: foodfolio.v1.ListSizesResponse
	(*UpdateSizeRequest)(nil),  // 6: foodfolio.v1.UpdateSizeRequest
	(*UpdateSizeResponse)(nil), // 7: foodfolio.v1.UpdateSizeResponse
	(*Timestamps)(nil),         // 8: foodfolio.v1.Timestamps
	(*PaginationRequest)(nil),  // 9: foodfolio.v1.PaginationRequest
	(*DeletedFilter)(nil),      // 10: foodfolio.v1.DeletedFilter
	(*PaginationResponse)(nil), // 11: foodfolio.v1.PaginationResponse
	(*IdRequest)(nil),          // 12: foodfolio.v1.IdRequest
	(*SuccessResponse)(nil),    // 13: foodfolio.v1.SuccessResponse
}
var file_size_proto_depIdxs = []int32{
	8,  // 0: foodfolio.v1.Size.timestamps:type_name -> foodfolio.v1.Timestamps
	0,  // 1: foodfolio.v1.CreateSizeResponse.size:type_name -> foodfolio.v1.Size
	0,  // 2: foodfolio.v1.GetSizeResponse.size:type_name -> foodfolio.v1.Size
	9,  // 3: foodfolio.v1.ListSizesRequest.pagination:type_name -> foodfolio.v1.PaginationRequest
	10, // 4: foodfolio.v1.ListSizesRequest.deleted_filter:type_name -> foodfolio.v1.DeletedFilter
	0,  // 5: foodfolio.v1.ListSizesResponse.sizes:type_name -> foodfolio.v1.Size
	11, // 6: foodfolio.v1.ListSizesResponse.pagination:type_name -> foodfolio.v1.PaginationResponse
	0,  // 7: foodfolio.v1.UpdateSizeResponse.size:type_name -> foodfolio.v1.Size
	1,  // 8: foodfolio.v1.SizeService.CreateSize:input_type -> foodfolio.v1.CreateSizeRequest
	12, // 9: foodfolio.v1.SizeService.GetSize:input_type -> foodfolio.v1.IdRequest
	4,  // 10: foodfolio.v1.SizeService.ListSizes:input_type -> foodfolio.v1.ListSizesRequest
	6,  // 11: foodfolio.v1.SizeService.UpdateSize:input_type -> foodfolio.v1.UpdateSizeRequest
	12, // 12: foodfolio.v1.SizeService.DeleteSize:input_type -> foodfolio.v1.IdRequest
	2,  // 13: foodfolio.v1.SizeService.CreateSize:output_type -> foodfolio.v1.CreateSizeResponse
	3,  // 14: foodfolio.v1.SizeService.GetSize:output_type -> foodfolio.v1.GetSizeResponse
	5,  // 15: foodfolio.v1.SizeService.ListSizes:output_type -> foodfolio.v1.ListSizesResponse
	7,  // 16: foodfolio.v1.SizeService.UpdateSize:output_type -> foodfolio.v1.UpdateSizeResponse
	13, // 17: foodfolio.v1.SizeService.DeleteSize:output_type -> foodfolio.v1.SuccessResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_size_proto_init() }
func file_size_proto_init() {
	if File_size_proto != nil {
		return
	}
	file_common_proto_init()
	file_size_proto_msgTypes[4].OneofWrappers = []any{}
	file_size_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_size_proto_rawDesc), len(file_size_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_size_proto_goTypes,
		DependencyIndexes: file_size_proto_depIdxs,
		MessageInfos:      file_size_proto_msgTypes,
	}.Build()
	File_size_proto = out.File
	file_size_proto_goTypes = nil
	file_size_proto_depIdxs = nil
}
