// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: type.proto

package foodfoliov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type (Packaging Type) message
type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // "Can", "PET Bottle", "Glass Bottle", "Box", "Bag"
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Timestamps    *Timestamps            `protobuf:"bytes,4,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	ItemCount     int32                  `protobuf:"varint,5,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"` // Number of items with this type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{0}
}

func (x *Type) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Type) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *Type) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

// Create type request
type CreateTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTypeRequest) Reset() {
	*x = CreateTypeRequest{}
	mi := &file_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTypeRequest) ProtoMessage() {}

func (x *CreateTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateTypeRequest) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Create type response
type CreateTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Type                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTypeResponse) Reset() {
	*x = CreateTypeResponse{}
	mi := &file_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTypeResponse) ProtoMessage() {}

func (x *CreateTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateTypeResponse) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTypeResponse) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

// Get type response
type GetTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Type                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeResponse) Reset() {
	*x = GetTypeResponse{}
	mi := &file_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeResponse) ProtoMessage() {}

func (x *GetTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeResponse.ProtoReflect.Descriptor instead.
func (*GetTypeResponse) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{3}
}

func (x *GetTypeResponse) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

// List types request
type ListTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *string                `protobuf:"bytes,1,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	DeletedFilter *DeletedFilter         `protobuf:"bytes,3,opt,name=deleted_filter,json=deletedFilter,proto3" json:"deleted_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesRequest) Reset() {
	*x = ListTypesRequest{}
	mi := &file_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesRequest) ProtoMessage() {}

func (x *ListTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesRequest.ProtoReflect.Descriptor instead.
func (*ListTypesRequest) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{4}
}

func (x *ListTypesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListTypesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTypesRequest) GetDeletedFilter() *DeletedFilter {
	if x != nil {
		return x.DeletedFilter
	}
	return nil
}

// List types response
type ListTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*Type                `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesResponse) Reset() {
	*x = ListTypesResponse{}
	mi := &file_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesResponse) ProtoMessage() {}

func (x *ListTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesResponse.ProtoReflect.Descriptor instead.
func (*ListTypesResponse) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{5}
}

func (x *ListTypesResponse) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ListTypesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Update type request
type UpdateTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTypeRequest) Reset() {
	*x = UpdateTypeRequest{}
	mi := &file_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeRequest) ProtoMessage() {}

func (x *UpdateTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTypeRequest) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Update type response
type UpdateTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Type                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTypeResponse) Reset() {
	*x = UpdateTypeResponse{}
	mi := &file_type_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeResponse) ProtoMessage() {}

func (x *UpdateTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateTypeResponse) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTypeResponse) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_type_proto protoreflect.FileDescriptor

const file_type_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"type.proto\x12\ffoodfolio.v1\x1a\fcommon.proto\"\x97\x01\n" +
	"\x04Type\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x128\n" +
	"\n" +
	"timestamps\x18\x04 \x01(\v2\x18.foodfolio.v1.TimestampsR\n" +
	"timestamps\x12\x1d\n" +
	"\n" +
	"item_count\x18\x05 \x01(\x05R\titemCount\"'\n" +
	"\x11CreateTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x12CreateTypeResponse\x12&\n" +
	"\x04type\x18\x01 \x01(\v2\x12.foodfolio.v1.TypeR\x04type\"9\n" +
	"\x0fGetTypeResponse\x12&\n" +
	"\x04type\x18\x01 \x01(\v2\x12.foodfolio.v1.TypeR\x04type\"\xbf\x01\n" +
	"\x10ListTypesRequest\x12\x1b\n" +
	"\x06search\x18\x01 \x01(\tH\x00R\x06search\x88\x01\x01\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.foodfolio.v1.PaginationRequestR\n" +
	"pagination\x12B\n" +
	"\x0edeleted_filter\x18\x03 \x01(\v2\x1b.foodfolio.v1.DeletedFilterR\rdeletedFilterB\t\n" +
	"\a_search\"\x7f\n" +
	"\x11ListTypesResponse\x12(\n" +
	"\x05types\x18\x01 \x03(\v2\x12.foodfolio.v1.TypeR\x05types\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .foodfolio.v1.PaginationResponseR\n" +
	"pagination\"7\n" +
	"\x11UpdateTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"<\n" +
	"\x12UpdateTypeResponse\x12&\n" +
	"\x04type\x18\x01 \x01(\v2\x12.foodfolio.v1.TypeR\x04type2\x86\x03\n" +
	"\vTypeService\x12O\n" +
	"\n" +
	"CreateType\x12\x1f.foodfolio.v1.CreateTypeRequest\x1a .foodfolio.v1.CreateTypeResponse\x12A\n" +
	"\aGetType\x12\x17.foodfolio.v1.IdRequest\x1a\x1d.foodfolio.v1.GetTypeResponse\x12L\n" +
	"\tListTypes\x12\x1e.foodfolio.v1.ListTypesRequest\x1a\x1f.foodfolio.v1.ListTypesResponse\x12O\n" +
	"\n" +
	"UpdateType\x12\x1f.foodfolio.v1.UpdateTypeRequest\x1a .foodfolio.v1.UpdateTypeResponse\x12D\n" +
	"\n" +
	"DeleteType\x12\x17.foodfolio.v1.IdRequest\x1a\x1d.foodfolio.v1.SuccessResponseBJZHtoxictoast/services/foodfolio-service/api/proto/foodfolio/v1;foodfoliov1b\x06proto3"

var (
	file_type_proto_rawDescOnce sync.Once
	file_type_proto_rawDescData []byte
)

func file_type_proto_rawDescGZIP() []byte {
	file_type_proto_rawDescOnce.Do(func() {
		file_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)))
	})
	return file_type_proto_rawDescData
}

var file_type_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_type_proto_goTypes = []any{
	(*Type)(nil),               // 0: foodfolio.v1.Type
	(*CreateTypeRequest)(nil),  // 1: foodfolio.v1.CreateTypeRequest
	(*CreateTypeResponse)(nil), // 2: foodfolio.v1.CreateTypeResponse
	(*GetTypeResponse)(nil),    // 3: foodfolio.v1.GetTypeResponse
	(*ListTypesRequest)(nil),   // 4: foodfolio.v1.ListTypesRequest
	(*ListTypesResponse)(nil),  // 5: foodfolio.v1.ListTypesResponse
	(*UpdateTypeRequest)(nil),  // 6: foodfolio.v1.UpdateTypeRequest
	(*UpdateTypeResponse)(nil), // 7: foodfolio.v1.UpdateTypeResponse
	(*Timestamps)(nil),         // 8: foodfolio.v1.Timestamps
	(*PaginationRequest)(nil),  // 9: foodfolio.v1.PaginationRequest
	(*DeletedFilter)(nil),      // 10: foodfolio.v1.DeletedFilter
	(*PaginationResponse)(nil), // 11: foodfolio.v1.PaginationResponse
	(*IdRequest)(nil),          // 12: foodfolio.v1.IdRequest
	(*SuccessResponse)(nil),    // 13: foodfolio.v1.SuccessResponse
}
var file_type_proto_depIdxs = []int32{
	8,  // 0: foodfolio.v1.Type.timestamps:type_name -> foodfolio.v1.Timestamps
	0,  // 1: foodfolio.v1.CreateTypeResponse.type:type_name -> foodfolio.v1.Type
	0,  // 2: foodfolio.v1.GetTypeResponse.type:type_name -> foodfolio.v1.Type
	9,  // 3: foodfolio.v1.ListTypesRequest.pagination:type_name -> foodfolio.v1.PaginationRequest
	10, // 4: foodfolio.v1.ListTypesRequest.deleted_filter:type_name -> foodfolio.v1.DeletedFilter
	0,  // 5: foodfolio.v1.ListTypesResponse.types:type_name -> foodfolio.v1.Type
	11, // 6: foodfolio.v1.ListTypesResponse.pagination:type_name -> foodfolio.v1.PaginationResponse
	0,  // 7: foodfolio.v1.UpdateTypeResponse.type:type_name -> foodfolio.v1.Type
	1,  // 8: foodfolio.v1.TypeService.CreateType:input_type -> foodfolio.v1.CreateTypeRequest
	12, // 9: foodfolio.v1.TypeService.GetType:input_type -> foodfolio.v1.IdRequest
	4,  // 10: foodfolio.v1.TypeService.ListTypes:input_type -> foodfolio.v1.ListTypesRequest
	6,  // 11: foodfolio.v1.TypeService.UpdateType:input_type -> foodfolio.v1.UpdateTypeRequest
	12, // 12: foodfolio.v1.TypeService.DeleteType:input_type -> foodfolio.v1.IdRequest
	2,  // 13: foodfolio.v1.TypeService.CreateType:output_type -> foodfolio.v1.CreateTypeResponse
	3,  // 14: foodfolio.v1.TypeService.GetType:output_type -> foodfolio.v1.GetTypeResponse
	5,  // 15: foodfolio.v1.TypeService.ListTypes:output_type -> foodfolio.v1.ListTypesResponse
	7,  // 16: foodfolio.v1.TypeService.UpdateType:output_type -> foodfolio.v1.UpdateTypeResponse
	13, // 17: foodfolio.v1.TypeService.DeleteType:output_type -> foodfolio.v1.SuccessResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_type_proto_init() }
func file_type_proto_init() {
	if File_type_proto != nil {
		return
	}
	file_common_proto_init()
	file_type_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_type_proto_goTypes,
		DependencyIndexes: file_type_proto_depIdxs,
		MessageInfos:      file_type_proto_msgTypes,
	}.Build()
	File_type_proto = out.File
	file_type_proto_goTypes = nil
	file_type_proto_depIdxs = nil
}
