// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/webhook.proto

package webhook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_PENDING     DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_SUCCESS     DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_RETRYING    DeliveryStatus = 4
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_PENDING",
		2: "DELIVERY_STATUS_SUCCESS",
		3: "DELIVERY_STATUS_FAILED",
		4: "DELIVERY_STATUS_RETRYING",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_PENDING":     1,
		"DELIVERY_STATUS_SUCCESS":     2,
		"DELIVERY_STATUS_FAILED":      3,
		"DELIVERY_STATUS_RETRYING":    4,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_webhook_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_api_proto_webhook_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{0}
}

type Webhook struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url               string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Secret            string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	EventTypes        []string               `protobuf:"bytes,4,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Active            bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	TotalDeliveries   int32                  `protobuf:"varint,7,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	SuccessDeliveries int32                  `protobuf:"varint,8,opt,name=success_deliveries,json=successDeliveries,proto3" json:"success_deliveries,omitempty"`
	FailedDeliveries  int32                  `protobuf:"varint,9,opt,name=failed_deliveries,json=failedDeliveries,proto3" json:"failed_deliveries,omitempty"`
	LastDeliveryAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_delivery_at,json=lastDeliveryAt,proto3" json:"last_delivery_at,omitempty"`
	LastSuccessAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"`
	LastFailureAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_failure_at,json=lastFailureAt,proto3" json:"last_failure_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_api_proto_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Webhook) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Webhook) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *Webhook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Webhook) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Webhook) GetTotalDeliveries() int32 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *Webhook) GetSuccessDeliveries() int32 {
	if x != nil {
		return x.SuccessDeliveries
	}
	return 0
}

func (x *Webhook) GetFailedDeliveries() int32 {
	if x != nil {
		return x.FailedDeliveries
	}
	return 0
}

func (x *Webhook) GetLastDeliveryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDeliveryAt
	}
	return nil
}

func (x *Webhook) GetLastSuccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessAt
	}
	return nil
}

func (x *Webhook) GetLastFailureAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFailureAt
	}
	return nil
}

func (x *Webhook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Webhook) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Delivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WebhookId     string                 `protobuf:"bytes,2,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventPayload  string                 `protobuf:"bytes,5,opt,name=event_payload,json=eventPayload,proto3" json:"event_payload,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=webhook.DeliveryStatus" json:"status,omitempty"`
	AttemptCount  int32                  `protobuf:"varint,7,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	NextRetryAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	LastAttemptAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_attempt_at,json=lastAttemptAt,proto3" json:"last_attempt_at,omitempty"`
	LastError     string                 `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_api_proto_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *Delivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delivery) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *Delivery) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Delivery) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Delivery) GetEventPayload() string {
	if x != nil {
		return x.EventPayload
	}
	return ""
}

func (x *Delivery) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *Delivery) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *Delivery) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

func (x *Delivery) GetLastAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptAt
	}
	return nil
}

func (x *Delivery) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Delivery) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Delivery) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeliveryAttempt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeliveryId     string                 `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	AttemptNumber  int32                  `protobuf:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	RequestUrl     string                 `protobuf:"bytes,4,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`
	ResponseStatus int32                  `protobuf:"varint,5,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseBody   string                 `protobuf:"bytes,6,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	Success        bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DurationMs     int32                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliveryAttempt) Reset() {
	*x = DeliveryAttempt{}
	mi := &file_api_proto_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAttempt) ProtoMessage() {}

func (x *DeliveryAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAttempt.ProtoReflect.Descriptor instead.
func (*DeliveryAttempt) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryAttempt) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryAttempt) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *DeliveryAttempt) GetRequestUrl() string {
	if x != nil {
		return x.RequestUrl
	}
	return ""
}

func (x *DeliveryAttempt) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *DeliveryAttempt) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *DeliveryAttempt) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliveryAttempt) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryAttempt) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *DeliveryAttempt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	EventTypes    []string               `protobuf:"bytes,3,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookRequest) Reset() {
	*x = CreateWebhookRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookRequest) ProtoMessage() {}

func (x *CreateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookRequest.ProtoReflect.Descriptor instead.
func (*CreateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWebhookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateWebhookRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreateWebhookRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *CreateWebhookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type WebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookResponse) Reset() {
	*x = WebhookResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookResponse) ProtoMessage() {}

func (x *WebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookResponse.ProtoReflect.Descriptor instead.
func (*WebhookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{4}
}

func (x *WebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type GetWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookRequest) Reset() {
	*x = GetWebhookRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookRequest) ProtoMessage() {}

func (x *GetWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{5}
}

func (x *GetWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWebhooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,3,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{6}
}

func (x *ListWebhooksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWebhooksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListWebhooksRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListWebhooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhooks      []*Webhook             `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{7}
}

func (x *ListWebhooksResponse) GetWebhooks() []*Webhook {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *ListWebhooksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWebhooksResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWebhooksResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	EventTypes    []string               `protobuf:"bytes,4,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebhookRequest) Reset() {
	*x = UpdateWebhookRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookRequest) ProtoMessage() {}

func (x *UpdateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebhookRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWebhookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateWebhookRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UpdateWebhookRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *UpdateWebhookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWebhookRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type DeleteWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookRequest) Reset() {
	*x = DeleteWebhookRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookRequest) ProtoMessage() {}

func (x *DeleteWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookResponse) Reset() {
	*x = DeleteWebhookResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookResponse) ProtoMessage() {}

func (x *DeleteWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebhookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ToggleWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleWebhookRequest) Reset() {
	*x = ToggleWebhookRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleWebhookRequest) ProtoMessage() {}

func (x *ToggleWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleWebhookRequest.ProtoReflect.Descriptor instead.
func (*ToggleWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{11}
}

func (x *ToggleWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToggleWebhookRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type RegenerateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateSecretRequest) Reset() {
	*x = RegenerateSecretRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateSecretRequest) ProtoMessage() {}

func (x *RegenerateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateSecretRequest.ProtoReflect.Descriptor instead.
func (*RegenerateSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{12}
}

func (x *RegenerateSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookRequest) Reset() {
	*x = TestWebhookRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookRequest) ProtoMessage() {}

func (x *TestWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookRequest.ProtoReflect.Descriptor instead.
func (*TestWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{13}
}

func (x *TestWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,3,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookResponse) Reset() {
	*x = TestWebhookResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookResponse) ProtoMessage() {}

func (x *TestWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookResponse.ProtoReflect.Descriptor instead.
func (*TestWebhookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{14}
}

func (x *TestWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestWebhookResponse) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

type GetDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryRequest) Reset() {
	*x = GetDeliveryRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryRequest) ProtoMessage() {}

func (x *GetDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{15}
}

func (x *GetDeliveryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Attempts      []*DeliveryAttempt     `protobuf:"bytes,2,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryResponse) Reset() {
	*x = DeliveryResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResponse) ProtoMessage() {}

func (x *DeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResponse.ProtoReflect.Descriptor instead.
func (*DeliveryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{16}
}

func (x *DeliveryResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *DeliveryResponse) GetAttempts() []*DeliveryAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

type ListDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookId     string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=webhook.DeliveryStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesRequest) Reset() {
	*x = ListDeliveriesRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesRequest) ProtoMessage() {}

func (x *ListDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{17}
}

func (x *ListDeliveriesRequest) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *ListDeliveriesRequest) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *ListDeliveriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeliveriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesResponse) Reset() {
	*x = ListDeliveriesResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesResponse) ProtoMessage() {}

func (x *ListDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{18}
}

func (x *ListDeliveriesResponse) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *ListDeliveriesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDeliveriesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeliveriesResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RetryDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDeliveryRequest) Reset() {
	*x = RetryDeliveryRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDeliveryRequest) ProtoMessage() {}

func (x *RetryDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDeliveryRequest.ProtoReflect.Descriptor instead.
func (*RetryDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{19}
}

func (x *RetryDeliveryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetryDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDeliveryResponse) Reset() {
	*x = RetryDeliveryResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDeliveryResponse) ProtoMessage() {}

func (x *RetryDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDeliveryResponse.ProtoReflect.Descriptor instead.
func (*RetryDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{20}
}

func (x *RetryDeliveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetryDeliveryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeliveryRequest) Reset() {
	*x = DeleteDeliveryRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeliveryRequest) ProtoMessage() {}

func (x *DeleteDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeliveryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteDeliveryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeliveryResponse) Reset() {
	*x = DeleteDeliveryResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeliveryResponse) ProtoMessage() {}

func (x *DeleteDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeliveryResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteDeliveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDeliveryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CleanupOldDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OlderThanDays int32                  `protobuf:"varint,1,opt,name=older_than_days,json=olderThanDays,proto3" json:"older_than_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupOldDeliveriesRequest) Reset() {
	*x = CleanupOldDeliveriesRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupOldDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupOldDeliveriesRequest) ProtoMessage() {}

func (x *CleanupOldDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupOldDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*CleanupOldDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{23}
}

func (x *CleanupOldDeliveriesRequest) GetOlderThanDays() int32 {
	if x != nil {
		return x.OlderThanDays
	}
	return 0
}

type CleanupOldDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupOldDeliveriesResponse) Reset() {
	*x = CleanupOldDeliveriesResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupOldDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupOldDeliveriesResponse) ProtoMessage() {}

func (x *CleanupOldDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupOldDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*CleanupOldDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{24}
}

func (x *CleanupOldDeliveriesResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *CleanupOldDeliveriesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetQueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatusRequest) Reset() {
	*x = GetQueueStatusRequest{}
	mi := &file_api_proto_webhook_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusRequest) ProtoMessage() {}

func (x *GetQueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{25}
}

type GetQueueStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeliveryQueueSize int32                  `protobuf:"varint,1,opt,name=delivery_queue_size,json=deliveryQueueSize,proto3" json:"delivery_queue_size,omitempty"`
	RetryQueueSize    int32                  `protobuf:"varint,2,opt,name=retry_queue_size,json=retryQueueSize,proto3" json:"retry_queue_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetQueueStatusResponse) Reset() {
	*x = GetQueueStatusResponse{}
	mi := &file_api_proto_webhook_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusResponse) ProtoMessage() {}

func (x *GetQueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_webhook_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusResponse.ProtoReflect.Descriptor instead.
func (*GetQueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_webhook_proto_rawDescGZIP(), []int{26}
}

func (x *GetQueueStatusResponse) GetDeliveryQueueSize() int32 {
	if x != nil {
		return x.DeliveryQueueSize
	}
	return 0
}

func (x *GetQueueStatusResponse) GetRetryQueueSize() int32 {
	if x != nil {
		return x.RetryQueueSize
	}
	return 0
}

var File_api_proto_webhook_proto protoreflect.FileDescriptor

const file_api_proto_webhook_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/webhook.proto\x12\awebhook\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x04\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x1f\n" +
	"\vevent_types\x18\x04 \x03(\tR\n" +
	"eventTypes\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12)\n" +
	"\x10total_deliveries\x18\a \x01(\x05R\x0ftotalDeliveries\x12-\n" +
	"\x12success_deliveries\x18\b \x01(\x05R\x11successDeliveries\x12+\n" +
	"\x11failed_deliveries\x18\t \x01(\x05R\x10failedDeliveries\x12D\n" +
	"\x10last_delivery_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0elastDeliveryAt\x12B\n" +
	"\x0flast_success_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rlastSuccessAt\x12B\n" +
	"\x0flast_failure_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rlastFailureAt\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x87\x04\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x02 \x01(\tR\twebhookId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12#\n" +
	"\revent_payload\x18\x05 \x01(\tR\feventPayload\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.webhook.DeliveryStatusR\x06status\x12#\n" +
	"\rattempt_count\x18\a \x01(\x05R\fattemptCount\x12>\n" +
	"\rnext_retry_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt\x12B\n" +
	"\x0flast_attempt_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastAttemptAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf3\x02\n" +
	"\x0fDeliveryAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\x12%\n" +
	"\x0eattempt_number\x18\x03 \x01(\x05R\rattemptNumber\x12\x1f\n" +
	"\vrequest_url\x18\x04 \x01(\tR\n" +
	"requestUrl\x12'\n" +
	"\x0fresponse_status\x18\x05 \x01(\x05R\x0eresponseStatus\x12#\n" +
	"\rresponse_body\x18\x06 \x01(\tR\fresponseBody\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x05R\n" +
	"durationMs\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x83\x01\n" +
	"\x14CreateWebhookRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1f\n" +
	"\vevent_types\x18\x03 \x03(\tR\n" +
	"eventTypes\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"=\n" +
	"\x0fWebhookResponse\x12*\n" +
	"\awebhook\x18\x01 \x01(\v2\x10.webhook.WebhookR\awebhook\"#\n" +
	"\x11GetWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"d\n" +
	"\x13ListWebhooksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vactive_only\x18\x03 \x01(\bR\n" +
	"activeOnly\"\x88\x01\n" +
	"\x14ListWebhooksResponse\x12,\n" +
	"\bwebhooks\x18\x01 \x03(\v2\x10.webhook.WebhookR\bwebhooks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xab\x01\n" +
	"\x14UpdateWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x1f\n" +
	"\vevent_types\x18\x04 \x03(\tR\n" +
	"eventTypes\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"&\n" +
	"\x14DeleteWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15DeleteWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x14ToggleWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\")\n" +
	"\x17RegenerateSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12TestWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"j\n" +
	"\x13TestWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vdelivery_id\x18\x03 \x01(\tR\n" +
	"deliveryId\"$\n" +
	"\x12GetDeliveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x10DeliveryResponse\x12-\n" +
	"\bdelivery\x18\x01 \x01(\v2\x11.webhook.DeliveryR\bdelivery\x124\n" +
	"\battempts\x18\x02 \x03(\v2\x18.webhook.DeliveryAttemptR\battempts\"\x95\x01\n" +
	"\x15ListDeliveriesRequest\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.webhook.DeliveryStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x8f\x01\n" +
	"\x16ListDeliveriesResponse\x121\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x11.webhook.DeliveryR\n" +
	"deliveries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"&\n" +
	"\x14RetryDeliveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15RetryDeliveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\x15DeleteDeliveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16DeleteDeliveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x1bCleanupOldDeliveriesRequest\x12&\n" +
	"\x0folder_than_days\x18\x01 \x01(\x05R\rolderThanDays\"]\n" +
	"\x1cCleanupOldDeliveriesResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15GetQueueStatusRequest\"r\n" +
	"\x16GetQueueStatusResponse\x12.\n" +
	"\x13delivery_queue_size\x18\x01 \x01(\x05R\x11deliveryQueueSize\x12(\n" +
	"\x10retry_queue_size\x18\x02 \x01(\x05R\x0eretryQueueSize*\xa5\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17DELIVERY_STATUS_SUCCESS\x10\x02\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18DELIVERY_STATUS_RETRYING\x10\x042\xf3\x04\n" +
	"\x18WebhookManagementService\x12H\n" +
	"\rCreateWebhook\x12\x1d.webhook.CreateWebhookRequest\x1a\x18.webhook.WebhookResponse\x12B\n" +
	"\n" +
	"GetWebhook\x12\x1a.webhook.GetWebhookRequest\x1a\x18.webhook.WebhookResponse\x12K\n" +
	"\fListWebhooks\x12\x1c.webhook.ListWebhooksRequest\x1a\x1d.webhook.ListWebhooksResponse\x12H\n" +
	"\rUpdateWebhook\x12\x1d.webhook.UpdateWebhookRequest\x1a\x18.webhook.WebhookResponse\x12N\n" +
	"\rDeleteWebhook\x12\x1d.webhook.DeleteWebhookRequest\x1a\x1e.webhook.DeleteWebhookResponse\x12H\n" +
	"\rToggleWebhook\x12\x1d.webhook.ToggleWebhookRequest\x1a\x18.webhook.WebhookResponse\x12N\n" +
	"\x10RegenerateSecret\x12 .webhook.RegenerateSecretRequest\x1a\x18.webhook.WebhookResponse\x12H\n" +
	"\vTestWebhook\x12\x1b.webhook.TestWebhookRequest\x1a\x1c.webhook.TestWebhookResponse2\x86\x04\n" +
	"\x0fDeliveryService\x12E\n" +
	"\vGetDelivery\x12\x1b.webhook.GetDeliveryRequest\x1a\x19.webhook.DeliveryResponse\x12Q\n" +
	"\x0eListDeliveries\x12\x1e.webhook.ListDeliveriesRequest\x1a\x1f.webhook.ListDeliveriesResponse\x12N\n" +
	"\rRetryDelivery\x12\x1d.webhook.RetryDeliveryRequest\x1a\x1e.webhook.RetryDeliveryResponse\x12Q\n" +
	"\x0eDeleteDelivery\x12\x1e.webhook.DeleteDeliveryRequest\x1a\x1f.webhook.DeleteDeliveryResponse\x12c\n" +
	"\x14CleanupOldDeliveries\x12$.webhook.CleanupOldDeliveriesRequest\x1a%.webhook.CleanupOldDeliveriesResponse\x12Q\n" +
	"\x0eGetQueueStatus\x12\x1e.webhook.GetQueueStatusRequest\x1a\x1f.webhook.GetQueueStatusResponseB7Z5toxictoast/services/webhook-service/api/proto;webhookb\x06proto3"

var (
	file_api_proto_webhook_proto_rawDescOnce sync.Once
	file_api_proto_webhook_proto_rawDescData []byte
)

func file_api_proto_webhook_proto_rawDescGZIP() []byte {
	file_api_proto_webhook_proto_rawDescOnce.Do(func() {
		file_api_proto_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_webhook_proto_rawDesc), len(file_api_proto_webhook_proto_rawDesc)))
	})
	return file_api_proto_webhook_proto_rawDescData
}

var file_api_proto_webhook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_proto_webhook_proto_goTypes = []any{
	(DeliveryStatus)(0),                  // 0: webhook.DeliveryStatus
	(*Webhook)(nil),                      // 1: webhook.Webhook
	(*Delivery)(nil),                     // 2: webhook.Delivery
	(*DeliveryAttempt)(nil),              // 3: webhook.DeliveryAttempt
	(*CreateWebhookRequest)(nil),         // 4: webhook.CreateWebhookRequest
	(*WebhookResponse)(nil),              // 5: webhook.WebhookResponse
	(*GetWebhookRequest)(nil),            // 6: webhook.GetWebhookRequest
	(*ListWebhooksRequest)(nil),          // 7: webhook.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),         // 8: webhook.ListWebhooksResponse
	(*UpdateWebhookRequest)(nil),         // 9: webhook.UpdateWebhookRequest
	(*DeleteWebhookRequest)(nil),         // 10: webhook.DeleteWebhookRequest
	(*DeleteWebhookResponse)(nil),        // 11: webhook.DeleteWebhookResponse
	(*ToggleWebhookRequest)(nil),         // 12: webhook.ToggleWebhookRequest
	(*RegenerateSecretRequest)(nil),      // 13: webhook.RegenerateSecretRequest
	(*TestWebhookRequest)(nil),           // 14: webhook.TestWebhookRequest
	(*TestWebhookResponse)(nil),          // 15: webhook.TestWebhookResponse
	(*GetDeliveryRequest)(nil),           // 16: webhook.GetDeliveryRequest
	(*DeliveryResponse)(nil),             // 17: webhook.DeliveryResponse
	(*ListDeliveriesRequest)(nil),        // 18: webhook.ListDeliveriesRequest
	(*ListDeliveriesResponse)(nil),       // 19: webhook.ListDeliveriesResponse
	(*RetryDeliveryRequest)(nil),         // 20: webhook.RetryDeliveryRequest
	(*RetryDeliveryResponse)(nil),        // 21: webhook.RetryDeliveryResponse
	(*DeleteDeliveryRequest)(nil),        // 22: webhook.DeleteDeliveryRequest
	(*DeleteDeliveryResponse)(nil),       // 23: webhook.DeleteDeliveryResponse
	(*CleanupOldDeliveriesRequest)(nil),  // 24: webhook.CleanupOldDeliveriesRequest
	(*CleanupOldDeliveriesResponse)(nil), // 25: webhook.CleanupOldDeliveriesResponse
	(*GetQueueStatusRequest)(nil),        // 26: webhook.GetQueueStatusRequest
	(*GetQueueStatusResponse)(nil),       // 27: webhook.GetQueueStatusResponse
	(*timestamppb.Timestamp)(nil),        // 28: google.protobuf.Timestamp
}
var file_api_proto_webhook_proto_depIdxs = []int32{
	28, // 0: webhook.Webhook.last_delivery_at:type_name -> google.protobuf.Timestamp
	28, // 1: webhook.Webhook.last_success_at:type_name -> google.protobuf.Timestamp
	28, // 2: webhook.Webhook.last_failure_at:type_name -> google.protobuf.Timestamp
	28, // 3: webhook.Webhook.created_at:type_name -> google.protobuf.Timestamp
	28, // 4: webhook.Webhook.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: webhook.Delivery.status:type_name -> webhook.DeliveryStatus
	28, // 6: webhook.Delivery.next_retry_at:type_name -> google.protobuf.Timestamp
	28, // 7: webhook.Delivery.last_attempt_at:type_name -> google.protobuf.Timestamp
	28, // 8: webhook.Delivery.created_at:type_name -> google.protobuf.Timestamp
	28, // 9: webhook.Delivery.updated_at:type_name -> google.protobuf.Timestamp
	28, // 10: webhook.DeliveryAttempt.created_at:type_name -> google.protobuf.Timestamp
	1,  // 11: webhook.WebhookResponse.webhook:type_name -> webhook.Webhook
	1,  // 12: webhook.ListWebhooksResponse.webhooks:type_name -> webhook.Webhook
	2,  // 13: webhook.DeliveryResponse.delivery:type_name -> webhook.Delivery
	3,  // 14: webhook.DeliveryResponse.attempts:type_name -> webhook.DeliveryAttempt
	0,  // 15: webhook.ListDeliveriesRequest.status:type_name -> webhook.DeliveryStatus
	2,  // 16: webhook.ListDeliveriesResponse.deliveries:type_name -> webhook.Delivery
	4,  // 17: webhook.WebhookManagementService.CreateWebhook:input_type -> webhook.CreateWebhookRequest
	6,  // 18: webhook.WebhookManagementService.GetWebhook:input_type -> webhook.GetWebhookRequest
	7,  // 19: webhook.WebhookManagementService.ListWebhooks:input_type -> webhook.ListWebhooksRequest
	9,  // 20: webhook.WebhookManagementService.UpdateWebhook:input_type -> webhook.UpdateWebhookRequest
	10, // 21: webhook.WebhookManagementService.DeleteWebhook:input_type -> webhook.DeleteWebhookRequest
	12, // 22: webhook.WebhookManagementService.ToggleWebhook:input_type -> webhook.ToggleWebhookRequest
	13, // 23: webhook.WebhookManagementService.RegenerateSecret:input_type -> webhook.RegenerateSecretRequest
	14, // 24: webhook.WebhookManagementService.TestWebhook:input_type -> webhook.TestWebhookRequest
	16, // 25: webhook.DeliveryService.GetDelivery:input_type -> webhook.GetDeliveryRequest
	18, // 26: webhook.DeliveryService.ListDeliveries:input_type -> webhook.ListDeliveriesRequest
	20, // 27: webhook.DeliveryService.RetryDelivery:input_type -> webhook.RetryDeliveryRequest
	22, // 28: webhook.DeliveryService.DeleteDelivery:input_type -> webhook.DeleteDeliveryRequest
	24, // 29: webhook.DeliveryService.CleanupOldDeliveries:input_type -> webhook.CleanupOldDeliveriesRequest
	26, // 30: webhook.DeliveryService.GetQueueStatus:input_type -> webhook.GetQueueStatusRequest
	5,  // 31: webhook.WebhookManagementService.CreateWebhook:output_type -> webhook.WebhookResponse
	5,  // 32: webhook.WebhookManagementService.GetWebhook:output_type -> webhook.WebhookResponse
	8,  // 33: webhook.WebhookManagementService.ListWebhooks:output_type -> webhook.ListWebhooksResponse
	5,  // 34: webhook.WebhookManagementService.UpdateWebhook:output_type -> webhook.WebhookResponse
	11, // 35: webhook.WebhookManagementService.DeleteWebhook:output_type -> webhook.DeleteWebhookResponse
	5,  // 36: webhook.WebhookManagementService.ToggleWebhook:output_type -> webhook.WebhookResponse
	5,  // 37: webhook.WebhookManagementService.RegenerateSecret:output_type -> webhook.WebhookResponse
	15, // 38: webhook.WebhookManagementService.TestWebhook:output_type -> webhook.TestWebhookResponse
	17, // 39: webhook.DeliveryService.GetDelivery:output_type -> webhook.DeliveryResponse
	19, // 40: webhook.DeliveryService.ListDeliveries:output_type -> webhook.ListDeliveriesResponse
	21, // 41: webhook.DeliveryService.RetryDelivery:output_type -> webhook.RetryDeliveryResponse
	23, // 42: webhook.DeliveryService.DeleteDelivery:output_type -> webhook.DeleteDeliveryResponse
	25, // 43: webhook.DeliveryService.CleanupOldDeliveries:output_type -> webhook.CleanupOldDeliveriesResponse
	27, // 44: webhook.DeliveryService.GetQueueStatus:output_type -> webhook.GetQueueStatusResponse
	31, // [31:45] is the sub-list for method output_type
	17, // [17:31] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_proto_webhook_proto_init() }
func file_api_proto_webhook_proto_init() {
	if File_api_proto_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_webhook_proto_rawDesc), len(file_api_proto_webhook_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_webhook_proto_goTypes,
		DependencyIndexes: file_api_proto_webhook_proto_depIdxs,
		EnumInfos:         file_api_proto_webhook_proto_enumTypes,
		MessageInfos:      file_api_proto_webhook_proto_msgTypes,
	}.Build()
	File_api_proto_webhook_proto = out.File
	file_api_proto_webhook_proto_goTypes = nil
	file_api_proto_webhook_proto_depIdxs = nil
}
