// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: link.proto

package link

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Link entity
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortCode     string                 `protobuf:"bytes,3,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	CustomAlias   *string                `protobuf:"bytes,4,opt,name=custom_alias,json=customAlias,proto3,oneof" json:"custom_alias,omitempty"`
	Title         *string                `protobuf:"bytes,5,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ClickCount    int32                  `protobuf:"varint,9,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *Link) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *Link) GetCustomAlias() string {
	if x != nil && x.CustomAlias != nil {
		return *x.CustomAlias
	}
	return ""
}

func (x *Link) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Link) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Link) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Link) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Link) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Link) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Link) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// Click entity (Analytics)
type Click struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkId        string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referer       *string                `protobuf:"bytes,5,opt,name=referer,proto3,oneof" json:"referer,omitempty"`
	Country       *string                `protobuf:"bytes,6,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City          *string                `protobuf:"bytes,7,opt,name=city,proto3,oneof" json:"city,omitempty"`
	DeviceType    *string                `protobuf:"bytes,8,opt,name=device_type,json=deviceType,proto3,oneof" json:"device_type,omitempty"`
	ClickedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=clicked_at,json=clickedAt,proto3" json:"clicked_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click) Reset() {
	*x = Click{}
	mi := &file_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click) ProtoMessage() {}

func (x *Click) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click.ProtoReflect.Descriptor instead.
func (*Click) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{1}
}

func (x *Click) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Click) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *Click) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Click) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Click) GetReferer() string {
	if x != nil && x.Referer != nil {
		return *x.Referer
	}
	return ""
}

func (x *Click) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *Click) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Click) GetDeviceType() string {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return ""
}

func (x *Click) GetClickedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClickedAt
	}
	return nil
}

func (x *Click) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Link requests/responses
type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CustomAlias   *string                `protobuf:"bytes,2,opt,name=custom_alias,json=customAlias,proto3,oneof" json:"custom_alias,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetCustomAlias() string {
	if x != nil && x.CustomAlias != nil {
		return *x.CustomAlias
	}
	return ""
}

func (x *CreateLinkRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CreateLinkRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateLinkRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"` // Full URL like https://short.link/abc123
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_link_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *CreateLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_link_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{4}
}

func (x *GetLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLinkByShortCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkByShortCodeRequest) Reset() {
	*x = GetLinkByShortCodeRequest{}
	mi := &file_link_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkByShortCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkByShortCodeRequest) ProtoMessage() {}

func (x *GetLinkByShortCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkByShortCodeRequest.ProtoReflect.Descriptor instead.
func (*GetLinkByShortCodeRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{5}
}

func (x *GetLinkByShortCodeRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	mi := &file_link_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkResponse.ProtoReflect.Descriptor instead.
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{6}
}

func (x *GetLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type ListLinksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	IsActive       *bool                  `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	IncludeExpired *bool                  `protobuf:"varint,4,opt,name=include_expired,json=includeExpired,proto3,oneof" json:"include_expired,omitempty"`
	Search         *string                `protobuf:"bytes,5,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_link_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{7}
}

func (x *ListLinksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLinksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLinksRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListLinksRequest) GetIncludeExpired() bool {
	if x != nil && x.IncludeExpired != nil {
		return *x.IncludeExpired
	}
	return false
}

func (x *ListLinksRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*Link                `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_link_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{8}
}

func (x *ListLinksResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListLinksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListLinksResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLinksResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLinksResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type UpdateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl   *string                `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3,oneof" json:"original_url,omitempty"`
	CustomAlias   *string                `protobuf:"bytes,3,opt,name=custom_alias,json=customAlias,proto3,oneof" json:"custom_alias,omitempty"`
	Title         *string                `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	IsActive      *bool                  `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkRequest) Reset() {
	*x = UpdateLinkRequest{}
	mi := &file_link_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkRequest) ProtoMessage() {}

func (x *UpdateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkRequest) GetOriginalUrl() string {
	if x != nil && x.OriginalUrl != nil {
		return *x.OriginalUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetCustomAlias() string {
	if x != nil && x.CustomAlias != nil {
		return *x.CustomAlias
	}
	return ""
}

func (x *UpdateLinkRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateLinkRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateLinkRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *UpdateLinkRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type UpdateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkResponse) Reset() {
	*x = UpdateLinkResponse{}
	mi := &file_link_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkResponse) ProtoMessage() {}

func (x *UpdateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_link_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IncrementClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementClickRequest) Reset() {
	*x = IncrementClickRequest{}
	mi := &file_link_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementClickRequest) ProtoMessage() {}

func (x *IncrementClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementClickRequest.ProtoReflect.Descriptor instead.
func (*IncrementClickRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{12}
}

func (x *IncrementClickRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type IncrementClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClickCount    int32                  `protobuf:"varint,1,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementClickResponse) Reset() {
	*x = IncrementClickResponse{}
	mi := &file_link_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementClickResponse) ProtoMessage() {}

func (x *IncrementClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementClickResponse.ProtoReflect.Descriptor instead.
func (*IncrementClickResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{13}
}

func (x *IncrementClickResponse) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

// Analytics requests/responses
type GetLinkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkStatsRequest) Reset() {
	*x = GetLinkStatsRequest{}
	mi := &file_link_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkStatsRequest) ProtoMessage() {}

func (x *GetLinkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLinkStatsRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{14}
}

func (x *GetLinkStatsRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

type GetLinkStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LinkId          string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	TotalClicks     int32                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueIps       int32                  `protobuf:"varint,3,opt,name=unique_ips,json=uniqueIps,proto3" json:"unique_ips,omitempty"`
	ClicksToday     int32                  `protobuf:"varint,4,opt,name=clicks_today,json=clicksToday,proto3" json:"clicks_today,omitempty"`
	ClicksThisWeek  int32                  `protobuf:"varint,5,opt,name=clicks_this_week,json=clicksThisWeek,proto3" json:"clicks_this_week,omitempty"`
	ClicksThisMonth int32                  `protobuf:"varint,6,opt,name=clicks_this_month,json=clicksThisMonth,proto3" json:"clicks_this_month,omitempty"`
	ClicksByCountry map[string]int32       `protobuf:"bytes,7,rep,name=clicks_by_country,json=clicksByCountry,proto3" json:"clicks_by_country,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ClicksByDevice  map[string]int32       `protobuf:"bytes,8,rep,name=clicks_by_device,json=clicksByDevice,proto3" json:"clicks_by_device,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopReferers     []string               `protobuf:"bytes,9,rep,name=top_referers,json=topReferers,proto3" json:"top_referers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLinkStatsResponse) Reset() {
	*x = GetLinkStatsResponse{}
	mi := &file_link_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkStatsResponse) ProtoMessage() {}

func (x *GetLinkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkStatsResponse.ProtoReflect.Descriptor instead.
func (*GetLinkStatsResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{15}
}

func (x *GetLinkStatsResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetLinkStatsResponse) GetTotalClicks() int32 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *GetLinkStatsResponse) GetUniqueIps() int32 {
	if x != nil {
		return x.UniqueIps
	}
	return 0
}

func (x *GetLinkStatsResponse) GetClicksToday() int32 {
	if x != nil {
		return x.ClicksToday
	}
	return 0
}

func (x *GetLinkStatsResponse) GetClicksThisWeek() int32 {
	if x != nil {
		return x.ClicksThisWeek
	}
	return 0
}

func (x *GetLinkStatsResponse) GetClicksThisMonth() int32 {
	if x != nil {
		return x.ClicksThisMonth
	}
	return 0
}

func (x *GetLinkStatsResponse) GetClicksByCountry() map[string]int32 {
	if x != nil {
		return x.ClicksByCountry
	}
	return nil
}

func (x *GetLinkStatsResponse) GetClicksByDevice() map[string]int32 {
	if x != nil {
		return x.ClicksByDevice
	}
	return nil
}

func (x *GetLinkStatsResponse) GetTopReferers() []string {
	if x != nil {
		return x.TopReferers
	}
	return nil
}

type RecordClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referer       *string                `protobuf:"bytes,4,opt,name=referer,proto3,oneof" json:"referer,omitempty"`
	Country       *string                `protobuf:"bytes,5,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City          *string                `protobuf:"bytes,6,opt,name=city,proto3,oneof" json:"city,omitempty"`
	DeviceType    *string                `protobuf:"bytes,7,opt,name=device_type,json=deviceType,proto3,oneof" json:"device_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordClickRequest) Reset() {
	*x = RecordClickRequest{}
	mi := &file_link_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordClickRequest) ProtoMessage() {}

func (x *RecordClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordClickRequest.ProtoReflect.Descriptor instead.
func (*RecordClickRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{16}
}

func (x *RecordClickRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *RecordClickRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RecordClickRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RecordClickRequest) GetReferer() string {
	if x != nil && x.Referer != nil {
		return *x.Referer
	}
	return ""
}

func (x *RecordClickRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *RecordClickRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *RecordClickRequest) GetDeviceType() string {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return ""
}

type RecordClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Click         *Click                 `protobuf:"bytes,1,opt,name=click,proto3" json:"click,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordClickResponse) Reset() {
	*x = RecordClickResponse{}
	mi := &file_link_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordClickResponse) ProtoMessage() {}

func (x *RecordClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordClickResponse.ProtoReflect.Descriptor instead.
func (*RecordClickResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{17}
}

func (x *RecordClickResponse) GetClick() *Click {
	if x != nil {
		return x.Click
	}
	return nil
}

type GetLinkClicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkClicksRequest) Reset() {
	*x = GetLinkClicksRequest{}
	mi := &file_link_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkClicksRequest) ProtoMessage() {}

func (x *GetLinkClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkClicksRequest.ProtoReflect.Descriptor instead.
func (*GetLinkClicksRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{18}
}

func (x *GetLinkClicksRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetLinkClicksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLinkClicksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetLinkClicksRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetLinkClicksRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetLinkClicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clicks        []*Click               `protobuf:"bytes,1,rep,name=clicks,proto3" json:"clicks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkClicksResponse) Reset() {
	*x = GetLinkClicksResponse{}
	mi := &file_link_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkClicksResponse) ProtoMessage() {}

func (x *GetLinkClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkClicksResponse.ProtoReflect.Descriptor instead.
func (*GetLinkClicksResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{19}
}

func (x *GetLinkClicksResponse) GetClicks() []*Click {
	if x != nil {
		return x.Clicks
	}
	return nil
}

func (x *GetLinkClicksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetLinkClicksResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLinkClicksResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetLinkClicksResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetClicksByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClicksByDateRequest) Reset() {
	*x = GetClicksByDateRequest{}
	mi := &file_link_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClicksByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClicksByDateRequest) ProtoMessage() {}

func (x *GetClicksByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClicksByDateRequest.ProtoReflect.Descriptor instead.
func (*GetClicksByDateRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{20}
}

func (x *GetClicksByDateRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetClicksByDateRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetClicksByDateRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ClicksByDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // Format: YYYY-MM-DD
	Clicks        int32                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClicksByDate) Reset() {
	*x = ClicksByDate{}
	mi := &file_link_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClicksByDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClicksByDate) ProtoMessage() {}

func (x *ClicksByDate) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClicksByDate.ProtoReflect.Descriptor instead.
func (*ClicksByDate) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{21}
}

func (x *ClicksByDate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ClicksByDate) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

type GetClicksByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ClicksByDate        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalClicks   int32                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClicksByDateResponse) Reset() {
	*x = GetClicksByDateResponse{}
	mi := &file_link_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClicksByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClicksByDateResponse) ProtoMessage() {}

func (x *GetClicksByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClicksByDateResponse.ProtoReflect.Descriptor instead.
func (*GetClicksByDateResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{22}
}

func (x *GetClicksByDateResponse) GetData() []*ClicksByDate {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetClicksByDateResponse) GetTotalClicks() int32 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

// Common messages
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_link_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_link_proto protoreflect.FileDescriptor

const file_link_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"link.proto\x12\x04link\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x04\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"short_code\x18\x03 \x01(\tR\tshortCode\x12&\n" +
	"\fcustom_alias\x18\x04 \x01(\tH\x00R\vcustomAlias\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x05 \x01(\tH\x01R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x02R\vdescription\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\texpiresAt\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1f\n" +
	"\vclick_count\x18\t \x01(\x05R\n" +
	"clickCount\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x04R\tdeletedAt\x88\x01\x01B\x0f\n" +
	"\r_custom_aliasB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_expires_atB\r\n" +
	"\v_deleted_at\"\x92\x03\n" +
	"\x05Click\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\areferer\x18\x05 \x01(\tH\x00R\areferer\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x06 \x01(\tH\x01R\acountry\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\a \x01(\tH\x02R\x04city\x88\x01\x01\x12$\n" +
	"\vdevice_type\x18\b \x01(\tH\x03R\n" +
	"deviceType\x88\x01\x01\x129\n" +
	"\n" +
	"clicked_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tclickedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\n" +
	"\n" +
	"\b_refererB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_cityB\x0e\n" +
	"\f_device_type\"\x9a\x02\n" +
	"\x11CreateLinkRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12&\n" +
	"\fcustom_alias\x18\x02 \x01(\tH\x00R\vcustomAlias\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x01R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\texpiresAt\x88\x01\x01B\x0f\n" +
	"\r_custom_aliasB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_expires_at\"Q\n" +
	"\x12CreateLinkResponse\x12\x1e\n" +
	"\x04link\x18\x01 \x01(\v2\n" +
	".link.LinkR\x04link\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\" \n" +
	"\x0eGetLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x19GetLinkByShortCodeRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"1\n" +
	"\x0fGetLinkResponse\x12\x1e\n" +
	"\x04link\x18\x01 \x01(\v2\n" +
	".link.LinkR\x04link\"\xdd\x01\n" +
	"\x10ListLinksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\tis_active\x18\x03 \x01(\bH\x00R\bisActive\x88\x01\x01\x12,\n" +
	"\x0finclude_expired\x18\x04 \x01(\bH\x01R\x0eincludeExpired\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x05 \x01(\tH\x02R\x06search\x88\x01\x01B\f\n" +
	"\n" +
	"_is_activeB\x12\n" +
	"\x10_include_expiredB\t\n" +
	"\a_search\"\x9d\x01\n" +
	"\x11ListLinksResponse\x12 \n" +
	"\x05links\x18\x01 \x03(\v2\n" +
	".link.LinkR\x05links\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\xf0\x02\n" +
	"\x11UpdateLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\foriginal_url\x18\x02 \x01(\tH\x00R\voriginalUrl\x88\x01\x01\x12&\n" +
	"\fcustom_alias\x18\x03 \x01(\tH\x01R\vcustomAlias\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tH\x02R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\texpiresAt\x88\x01\x01\x12 \n" +
	"\tis_active\x18\a \x01(\bH\x05R\bisActive\x88\x01\x01B\x0f\n" +
	"\r_original_urlB\x0f\n" +
	"\r_custom_aliasB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_expires_atB\f\n" +
	"\n" +
	"_is_active\"4\n" +
	"\x12UpdateLinkResponse\x12\x1e\n" +
	"\x04link\x18\x01 \x01(\v2\n" +
	".link.LinkR\x04link\"#\n" +
	"\x11DeleteLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x15IncrementClickRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"9\n" +
	"\x16IncrementClickResponse\x12\x1f\n" +
	"\vclick_count\x18\x01 \x01(\x05R\n" +
	"clickCount\".\n" +
	"\x13GetLinkStatsRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\"\xcb\x04\n" +
	"\x14GetLinkStatsResponse\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x05R\vtotalClicks\x12\x1d\n" +
	"\n" +
	"unique_ips\x18\x03 \x01(\x05R\tuniqueIps\x12!\n" +
	"\fclicks_today\x18\x04 \x01(\x05R\vclicksToday\x12(\n" +
	"\x10clicks_this_week\x18\x05 \x01(\x05R\x0eclicksThisWeek\x12*\n" +
	"\x11clicks_this_month\x18\x06 \x01(\x05R\x0fclicksThisMonth\x12[\n" +
	"\x11clicks_by_country\x18\a \x03(\v2/.link.GetLinkStatsResponse.ClicksByCountryEntryR\x0fclicksByCountry\x12X\n" +
	"\x10clicks_by_device\x18\b \x03(\v2..link.GetLinkStatsResponse.ClicksByDeviceEntryR\x0eclicksByDevice\x12!\n" +
	"\ftop_referers\x18\t \x03(\tR\vtopReferers\x1aB\n" +
	"\x14ClicksByCountryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aA\n" +
	"\x13ClicksByDeviceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x99\x02\n" +
	"\x12RecordClickRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\areferer\x18\x04 \x01(\tH\x00R\areferer\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x05 \x01(\tH\x01R\acountry\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x06 \x01(\tH\x02R\x04city\x88\x01\x01\x12$\n" +
	"\vdevice_type\x18\a \x01(\tH\x03R\n" +
	"deviceType\x88\x01\x01B\n" +
	"\n" +
	"\b_refererB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_cityB\x0e\n" +
	"\f_device_type\"8\n" +
	"\x13RecordClickResponse\x12!\n" +
	"\x05click\x18\x01 \x01(\v2\v.link.ClickR\x05click\"\xf8\x01\n" +
	"\x14GetLinkClicksRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12>\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartDate\x88\x01\x01\x12:\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendDate\x88\x01\x01B\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_date\"\xa4\x01\n" +
	"\x15GetLinkClicksResponse\x12#\n" +
	"\x06clicks\x18\x01 \x03(\v2\v.link.ClickR\x06clicks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\xa3\x01\n" +
	"\x16GetClicksByDateRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\":\n" +
	"\fClicksByDate\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x05R\x06clicks\"d\n" +
	"\x17GetClicksByDateResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.link.ClicksByDateR\x04data\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x05R\vtotalClicks\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x82\x06\n" +
	"\vLinkService\x12?\n" +
	"\n" +
	"CreateLink\x12\x17.link.CreateLinkRequest\x1a\x18.link.CreateLinkResponse\x126\n" +
	"\aGetLink\x12\x14.link.GetLinkRequest\x1a\x15.link.GetLinkResponse\x12L\n" +
	"\x12GetLinkByShortCode\x12\x1f.link.GetLinkByShortCodeRequest\x1a\x15.link.GetLinkResponse\x12<\n" +
	"\tListLinks\x12\x16.link.ListLinksRequest\x1a\x17.link.ListLinksResponse\x12?\n" +
	"\n" +
	"UpdateLink\x12\x17.link.UpdateLinkRequest\x1a\x18.link.UpdateLinkResponse\x12;\n" +
	"\n" +
	"DeleteLink\x12\x17.link.DeleteLinkRequest\x1a\x14.link.DeleteResponse\x12K\n" +
	"\x0eIncrementClick\x12\x1b.link.IncrementClickRequest\x1a\x1c.link.IncrementClickResponse\x12E\n" +
	"\fGetLinkStats\x12\x19.link.GetLinkStatsRequest\x1a\x1a.link.GetLinkStatsResponse\x12B\n" +
	"\vRecordClick\x12\x18.link.RecordClickRequest\x1a\x19.link.RecordClickResponse\x12H\n" +
	"\rGetLinkClicks\x12\x1a.link.GetLinkClicksRequest\x1a\x1b.link.GetLinkClicksResponse\x12N\n" +
	"\x0fGetClicksByDate\x12\x1c.link.GetClicksByDateRequest\x1a\x1d.link.GetClicksByDateResponseB1Z/toxictoast/services/link-service/api/proto/linkb\x06proto3"

var (
	file_link_proto_rawDescOnce sync.Once
	file_link_proto_rawDescData []byte
)

func file_link_proto_rawDescGZIP() []byte {
	file_link_proto_rawDescOnce.Do(func() {
		file_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_link_proto_rawDesc), len(file_link_proto_rawDesc)))
	})
	return file_link_proto_rawDescData
}

var file_link_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_link_proto_goTypes = []any{
	(*Link)(nil),                      // 0: link.Link
	(*Click)(nil),                     // 1: link.Click
	(*CreateLinkRequest)(nil),         // 2: link.CreateLinkRequest
	(*CreateLinkResponse)(nil),        // 3: link.CreateLinkResponse
	(*GetLinkRequest)(nil),            // 4: link.GetLinkRequest
	(*GetLinkByShortCodeRequest)(nil), // 5: link.GetLinkByShortCodeRequest
	(*GetLinkResponse)(nil),           // 6: link.GetLinkResponse
	(*ListLinksRequest)(nil),          // 7: link.ListLinksRequest
	(*ListLinksResponse)(nil),         // 8: link.ListLinksResponse
	(*UpdateLinkRequest)(nil),         // 9: link.UpdateLinkRequest
	(*UpdateLinkResponse)(nil),        // 10: link.UpdateLinkResponse
	(*DeleteLinkRequest)(nil),         // 11: link.DeleteLinkRequest
	(*IncrementClickRequest)(nil),     // 12: link.IncrementClickRequest
	(*IncrementClickResponse)(nil),    // 13: link.IncrementClickResponse
	(*GetLinkStatsRequest)(nil),       // 14: link.GetLinkStatsRequest
	(*GetLinkStatsResponse)(nil),      // 15: link.GetLinkStatsResponse
	(*RecordClickRequest)(nil),        // 16: link.RecordClickRequest
	(*RecordClickResponse)(nil),       // 17: link.RecordClickResponse
	(*GetLinkClicksRequest)(nil),      // 18: link.GetLinkClicksRequest
	(*GetLinkClicksResponse)(nil),     // 19: link.GetLinkClicksResponse
	(*GetClicksByDateRequest)(nil),    // 20: link.GetClicksByDateRequest
	(*ClicksByDate)(nil),              // 21: link.ClicksByDate
	(*GetClicksByDateResponse)(nil),   // 22: link.GetClicksByDateResponse
	(*DeleteResponse)(nil),            // 23: link.DeleteResponse
	nil,                               // 24: link.GetLinkStatsResponse.ClicksByCountryEntry
	nil,                               // 25: link.GetLinkStatsResponse.ClicksByDeviceEntry
	(*timestamppb.Timestamp)(nil),     // 26: google.protobuf.Timestamp
}
var file_link_proto_depIdxs = []int32{
	26, // 0: link.Link.expires_at:type_name -> google.protobuf.Timestamp
	26, // 1: link.Link.created_at:type_name -> google.protobuf.Timestamp
	26, // 2: link.Link.updated_at:type_name -> google.protobuf.Timestamp
	26, // 3: link.Link.deleted_at:type_name -> google.protobuf.Timestamp
	26, // 4: link.Click.clicked_at:type_name -> google.protobuf.Timestamp
	26, // 5: link.Click.created_at:type_name -> google.protobuf.Timestamp
	26, // 6: link.CreateLinkRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: link.CreateLinkResponse.link:type_name -> link.Link
	0,  // 8: link.GetLinkResponse.link:type_name -> link.Link
	0,  // 9: link.ListLinksResponse.links:type_name -> link.Link
	26, // 10: link.UpdateLinkRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 11: link.UpdateLinkResponse.link:type_name -> link.Link
	24, // 12: link.GetLinkStatsResponse.clicks_by_country:type_name -> link.GetLinkStatsResponse.ClicksByCountryEntry
	25, // 13: link.GetLinkStatsResponse.clicks_by_device:type_name -> link.GetLinkStatsResponse.ClicksByDeviceEntry
	1,  // 14: link.RecordClickResponse.click:type_name -> link.Click
	26, // 15: link.GetLinkClicksRequest.start_date:type_name -> google.protobuf.Timestamp
	26, // 16: link.GetLinkClicksRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 17: link.GetLinkClicksResponse.clicks:type_name -> link.Click
	26, // 18: link.GetClicksByDateRequest.start_date:type_name -> google.protobuf.Timestamp
	26, // 19: link.GetClicksByDateRequest.end_date:type_name -> google.protobuf.Timestamp
	21, // 20: link.GetClicksByDateResponse.data:type_name -> link.ClicksByDate
	2,  // 21: link.LinkService.CreateLink:input_type -> link.CreateLinkRequest
	4,  // 22: link.LinkService.GetLink:input_type -> link.GetLinkRequest
	5,  // 23: link.LinkService.GetLinkByShortCode:input_type -> link.GetLinkByShortCodeRequest
	7,  // 24: link.LinkService.ListLinks:input_type -> link.ListLinksRequest
	9,  // 25: link.LinkService.UpdateLink:input_type -> link.UpdateLinkRequest
	11, // 26: link.LinkService.DeleteLink:input_type -> link.DeleteLinkRequest
	12, // 27: link.LinkService.IncrementClick:input_type -> link.IncrementClickRequest
	14, // 28: link.LinkService.GetLinkStats:input_type -> link.GetLinkStatsRequest
	16, // 29: link.LinkService.RecordClick:input_type -> link.RecordClickRequest
	18, // 30: link.LinkService.GetLinkClicks:input_type -> link.GetLinkClicksRequest
	20, // 31: link.LinkService.GetClicksByDate:input_type -> link.GetClicksByDateRequest
	3,  // 32: link.LinkService.CreateLink:output_type -> link.CreateLinkResponse
	6,  // 33: link.LinkService.GetLink:output_type -> link.GetLinkResponse
	6,  // 34: link.LinkService.GetLinkByShortCode:output_type -> link.GetLinkResponse
	8,  // 35: link.LinkService.ListLinks:output_type -> link.ListLinksResponse
	10, // 36: link.LinkService.UpdateLink:output_type -> link.UpdateLinkResponse
	23, // 37: link.LinkService.DeleteLink:output_type -> link.DeleteResponse
	13, // 38: link.LinkService.IncrementClick:output_type -> link.IncrementClickResponse
	15, // 39: link.LinkService.GetLinkStats:output_type -> link.GetLinkStatsResponse
	17, // 40: link.LinkService.RecordClick:output_type -> link.RecordClickResponse
	19, // 41: link.LinkService.GetLinkClicks:output_type -> link.GetLinkClicksResponse
	22, // 42: link.LinkService.GetClicksByDate:output_type -> link.GetClicksByDateResponse
	32, // [32:43] is the sub-list for method output_type
	21, // [21:32] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_link_proto_init() }
func file_link_proto_init() {
	if File_link_proto != nil {
		return
	}
	file_link_proto_msgTypes[0].OneofWrappers = []any{}
	file_link_proto_msgTypes[1].OneofWrappers = []any{}
	file_link_proto_msgTypes[2].OneofWrappers = []any{}
	file_link_proto_msgTypes[7].OneofWrappers = []any{}
	file_link_proto_msgTypes[9].OneofWrappers = []any{}
	file_link_proto_msgTypes[16].OneofWrappers = []any{}
	file_link_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_link_proto_rawDesc), len(file_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_link_proto_goTypes,
		DependencyIndexes: file_link_proto_depIdxs,
		MessageInfos:      file_link_proto_msgTypes,
	}.Build()
	File_link_proto = out.File
	file_link_proto_goTypes = nil
	file_link_proto_depIdxs = nil
}
